### ISSUE TITLE
[Controller Request]: razer raiju mobile

### ISSUE THREAD

**Issue by hagah15** [ndeadly/MissionControl#802] opened 2024-04-05 23:24 UTC
### Controller Name

razer raiju mobile 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

can you please add this controller

**Comment by ndeadly** [comment] 2024-04-05 23:27
This might be a bluetooth LE controller if it fails to pair. Come check out the experimental BLE builds on my discord server and see if it shows any signs of connecting with those https://discord.gg/gegfNZ5Ucz

**Comment by ndeadly** [comment] 2024-04-07 05:57
Just realised this is a duplicate of [#611](https://github.com/ndeadly/MissionControl/issues/611). Please direct any future correspondence to the original request.

**Closed by ndeadly** 2024-04-07 05:57 UTC
Labels: controller request
