### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by Neyatshi** [ndeadly/MissionControl#557] opened 2022-12-30 09:33 UTC
### Controller Name

Dualshock 3

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Sony Playstation

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment] 2022-12-30 10:44
Duplicate of #7

**Closed by ndeadly** 2022-12-30 10:44 UTC
Labels: controller request
