### ISSUE TITLE
[Bug Report]: WiiU pro controller  left stick doesn't calibrate 

### ISSUE THREAD

**Issue by dj-nest** [ndeadly/MissionControl#718] opened 2023-09-02 13:22 UTC
### Switch Firmware Version

16.1.0 (Latest)

### Atmosphère Version

1.5.5 (Latest)

### Mission Control Version

0.9.4 (Latest)

### Boot Method

Fusée

### Issue Description

I successfully connected the WiiU pro controller without any issues on the change grip order page .
I saw on the Readme file that it's good to recalibrate the sticks on 1st run. The right stick works perfect but the left one is a little bit off to the right. I tried to recalibrate the left sstick but on the calibration page it doest respond at all. The wiiu pro controller is an original one.

**Comment by ndeadly** [comment] 2023-09-02 13:47
This might be related to #682. I'm not sure on the cause, but try rotating the right stick for a few seconds when you first start calibrating. No idea why this works, but on my DS4 this will "unstick" the seemingly unresponsive stick

**Comment by dj-nest** [comment] 2023-09-02 22:09
I looked at the issue #682  and as many times I tried rotating the right stick, the left one I wanted to calibrate wouldn't respond at all. But in the 1st screen I noticed if I move the right stick it responds slightly with small movements.

**Comment by ndeadly** [comment] 2023-09-05 19:58
Just confirmed that my controller's left stick shows the same behaviour you described. However, I am able to use the trick I mentioned above with the other stick to make it work. In any case, this is a super strange issue that warrants further investigation when I have the time.

**Comment by dj-nest** [comment] 2023-09-06 12:26
Thanks for replying back. I managed to do the trick you said sliding the right stick on the right position simultaneously with the left stick and it took the calibration after some tries. Now it works as a treat.

**Comment by ndeadly** [comment] 2023-09-06 12:33
Nice one! I will close this issue in favour of #682 as I think it's the same issue, and not specific to the Wii U controller.

**Closed by ndeadly** 2023-09-06 12:33 UTC
