### ISSUE TITLE
Weird Static Sound when I open a certain menu in Splatoon 3

### ISSUE THREAD

**Issue by itsDarkEye** [ndeadly/MissionControl#538] opened 2022-11-06 09:56 UTC
### Switch Firmware Version

15.0.1 (Latest)

### Atmosphère Version

1.4.0 (Latest)

### Mission Control Version

0.8.0 (Latest)

### Boot Method

Hekate

### Issue Description

I've been playing splatoon for a while with no problems but recently when I updated to 15.0.1, I hear a weird static noise that happens when I open a certain menu in-game and therefore leads the console into a crash. I suppose it is because of the missing amiibo data because that menu used to prompt an error saying that I am unable to scan an amiibo and now, it crashes my game. I tested and I'm sure it's due to missioncontrol because it only happrns when I connect my dualsense controller to the console. Thanks in advance.

**Comment by itsDarkEye** [comment] 2022-11-06 09:58
I've tried another game with an amiibo prompt and also crashed my game. I cannot ignore this because this is an important menu to access when changing gear, weapons

**Comment by ndeadly** [comment] 2022-11-06 11:52
This has already been reported here https://github.com/ndeadly/MissionControl/issues/524 and is likely just another manifestation of the issue you reported in https://github.com/ndeadly/MissionControl/issues/511

It's caused by incorrectly responding to requests for NFC data. I've been looking into a solution for it, but got caught up working on support for 15.0.0 in the past couple of weeks.

**Comment by itsDarkEye** [comment] 2022-11-06 13:35
Yep I reported that before. A mere little pop-up turned into a kill switch. I hope you will be able to solve this 👍

**Comment by iCanuck** [comment] 2023-02-21 06:09
> This has already been reported here #524 and is likely just another manifestation of the issue you reported in #511
> 
> It's caused by incorrectly responding to requests for NFC data. I've been looking into a solution for it, but got caught up working on support for 15.0.0 in the past couple of weeks.

I see you disabled nfc temporarily in commit -https://github.com/ndeadly/MissionControl/commit/d5aa066fea3133430e528c99587e8209b36161ca

Any way you could compile the dev branch for people with this issue?

**Comment by ndeadly** [comment] 2023-02-21 09:50
I was planning to make a bugfix release including it this week, but now 16.0.0 is out it doesn't really make sense to make a minor release.

So here you go. Maybe you (or someone else) can confirm it does actually fix the issue before I push out an official release.
[MissionControl-0.8.0-nfc-fix-f358600.zip](https://github.com/ndeadly/MissionControl/files/10792143/MissionControl-0.8.0-nfc-fix-f358600.zip)

**Comment by iCanuck** [comment] 2023-02-21 17:21
> I was planning to make a bugfix release including it this week, but now 16.0.0 is out it doesn't really make sense to make a minor release.
> 
> So here you go. Maybe you (or someone else) can confirm it does actually fix the issue before I push out an official release. [MissionControl-0.8.0-nfc-fix-f358600.zip](https://github.com/ndeadly/MissionControl/files/10792143/MissionControl-0.8.0-nfc-fix-f358600.zip)

Thanks! I will test and report back.

**Comment by iCanuck** [comment] 2023-02-21 18:56
> I was planning to make a bugfix release including it this week, but now 16.0.0 is out it doesn't really make sense to make a minor release.
> 
> So here you go. Maybe you (or someone else) can confirm it does actually fix the issue before I push out an official release. [MissionControl-0.8.0-nfc-fix-f358600.zip](https://github.com/ndeadly/MissionControl/files/10792143/MissionControl-0.8.0-nfc-fix-f358600.zip)

This issue is no longer present in the nfc fix. I did get one panic while trying to connect my xbox one controller however this may be unrelated, the report is below.

[report_09f1a150a.zip](https://github.com/ndeadly/MissionControl/files/10796660/report_09f1a150a.zip)

Not sure if this is relevant to missioncontrol or just an issue with cfw and being offline playing splatoon 3 but I am still getting error code 2115-0012 "An error occurred while trying to access the amiibo. Please try again"

**Comment by ndeadly** [comment] 2023-02-21 19:21
> I did get one panic while trying to connect my xbox one controller however this may be unrelated, the report is below.

Probably unrelated, as there shouldn't be anything going on with nfc when you're pairing. Ignoring the nfc data was also the normal behaviour prior to whenever I introduced the changes that caused this issue in the first place, and there weren't any issues that I know of. Unfortunately I didn't keep the .elf for this build, so I can't look to see exactly where it crashed. I would put it down to random chance for now. If it happens again when I make the new release, please open a new issue for it and I'll look into it.

> but I am still getting error code 2115-0012 "An error occurred while trying to access the amiibo. Please try again"

Yeah this kind of thing is still expected. It's what handling the nfc packets was supposed to fix to begin with. That will be a problem until I find the time to properly emulate the nfc responses, but at least it's better than glitchy audio and freezing.

**Comment by iCanuck** [comment] 2023-02-21 22:07
> > I did get one panic while trying to connect my xbox one controller however this may be unrelated, the report is below.
> 
> Probably unrelated, as there shouldn't be anything going on with nfc when you're pairing. Ignoring the nfc data was also the normal behaviour prior to whenever I introduced the changes that caused this issue in the first place, and there weren't any issues that I know of. Unfortunately I didn't keep the .elf for this build, so I can't look to see exactly where it crashed. I would put it down to random chance for now. If it happens again when I make the new release, please open a new issue for it and I'll look into it.
> 
> > but I am still getting error code 2115-0012 "An error occurred while trying to access the amiibo. Please try again"
> 
> Yeah this kind of thing is still expected. It's what handling the nfc packets was supposed to fix to begin with. That will be a problem until I find the time to properly emulate the nfc responses, but at least it's better than glitchy audio and freezing.

Sounds good I will monitor on future builds.

Makes sense if the game can’t access the nfc data.

Thank you, appreciate all the work you put into this.

**Comment by ndeadly** [comment] 2023-02-24 00:42
This fix is now merged into the latest release.

**Closed by ndeadly** 2023-02-24 00:42 UTC
