### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by clairbuoyancy** [ndeadly/MissionControl#684] opened 2023-08-21 04:11 UTC
### Controller Name

Stadia Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

the stadia Controller being compatible with other devices is a somewhat new update, and the controller has to be converted from the proprietary stadia format to Bluetooth. it should be read as a generic Bluetooth but it's not even connecting.

**Comment by ndeadly** [comment] 2023-08-21 06:18
Duplicate of #568

**Closed** 2023-08-21 06:18 UTC
Labels: controller request
