### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by lordgumis** [ndeadly/MissionControl#661] opened 2023-06-13 06:22 UTC
### Controller Name

Google Stadia with bluetooth activated 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment] 2023-06-13 06:32
Duplicate of #568

**Closed** 2023-06-13 06:32 UTC
Labels: controller request
