### ISSUE TITLE
[Controller Request]: for Google stadia controller

### ISSUE THREAD

**Issue by ducklinggg24** [ndeadly/MissionControl#892] opened 2024-11-23 14:59 UTC
### Controller Name

Google stadia controller

### Current Controller Behaviour

Other (please specify below)

### Controller vendor and product ID

18d1:9400

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

Stadia controller does not even show up to be able to paired. But it can be paired for PC or chromecast with google tv or any Bluetooth enabled devices without a problem.

**Comment by ndeadly** [comment] 2024-11-27 15:06
Duplicate of #568

**Closed by ndeadly** 2024-11-27 15:06 UTC
Labels: controller request
