### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by nano02g** [ndeadly/MissionControl#658] opened 2023-06-11 16:39 UTC
### Controller Name

Ps3 Dualshok

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Input Report Format

How can i can conect the ps3 controller with the switch i tried but i cant

**Comment by SpeckyYT** [comment] 2023-06-12 05:08
Wait, the PS3 doesn't support rumble?
Also, this is a duplicate of #7 (yes, it's already implemented)

**Comment by ndeadly** [comment] 2023-06-12 07:22
The issue tracker is for reporting bugs, please don't use it for support questions.

The Dualshock 3 controller is already supported and information on how to connect it can be found [here](https://github.com/ndeadly/MissionControl#pairing-controllers)

If you are following the above and it still doesn't work you either a) are using an unofficial DS3 clone that isn't supported, or b) something else is wrong with your setup (MC not running, bad USB cable etc.)

**Closed by ndeadly** 2023-06-12 07:22 UTC
Labels: controller request
