### ISSUE TITLE
[Feature Request]: Wii Remote motion support for Nintendo Switch Sports

### ISSUE THREAD

**Issue by FlareBlitz17** [ndeadly/MissionControl#458] opened 2022-04-27 23:05 UTC
### Feature Description

Is there plans to get Wii Remote motion support working for Nintendo Switch Sports? I understand that all controller so far act as pro controller when they are synced to the controller, so I suppose it won't be added until there is a way to identify a Wiimote as a joycon?

### Rationale

For the Nintendo Switch Sports game, i.e. tennis

**Comment by ndeadly** [comment] 2022-04-28 00:05
This is essentially a duplicate of https://github.com/ndeadly/MissionControl/issues/108

It's not really an issue of supporting a specific game or controller, more the general issue of having the ability to identify controllers as joycons. When that works and controller could be used. 

It can be done, and I have done some work on it. It will be added when a few issues have been stomped out and I have an applet/overlay ready to facilitate easy switching between controller types.

**Closed by ndeadly** 2022-04-28 00:05 UTC
Labels: feature request
