### ISSUE TITLE
[Bug Report]: 3rd party ps4 controller randomly disconnects

### ISSUE THREAD

**Issue by Webhead2130** [ndeadly/MissionControl#430] opened 2022-02-20 07:16 UTC
### Switch Firmware Version

13.2.1 (Latest)

### Atmosphère Version

1.2.6 (Latest)

### Mission Control Version

0.6.4 (Latest)

### Boot Method

Hekate

### Issue Description

I believe I’m using a 3rd party ds4 controller because it randomly disconnects while I’m in the middle of playing a game. I know it’s not the battery because it happens sometimes right after I recharge it. I tried to use your older builds but it crashes on boot up. At first the controller disconnects and then I’m able to reconnect it quickly but at some point it stops connecting on altogether and the controller shuts off as soon as I try to turn it back on. It gets to the point to where I have to stay connected to the usb with a cord in it in order for it to work sometimes. This is an issue I’ve had for awhile and I’ve been trying to look through older discussions to see if there’s a fix for it.

**Comment by Masamune3210** [comment] 2022-02-20 08:39
Unfortunately some controllers especially third party ones don't adhere to the controller behaviour they are trying to mimic very well, hopefully your controller can be added

**Comment by Webhead2130** [comment] 2022-02-20 22:55
Yeah, I thought so but, I don’t think there’s anything too different from a standard one though

**Comment by ndeadly** [comment] 2022-02-21 01:13
This is a known problem for some third party PS4 controllers. They use a different chipset that doesn't support a broadcom vendor command sent by the console. Unfortunately there is no way to distinguish them from the official Sony controllers from the software side, so manually disabling the command on a per controller basis is required.

See https://github.com/ndeadly/MissionControl/issues/342#issuecomment-954172676

**Comment by Webhead2130** [comment] 2022-02-23 06:16
Is there anything that can be done hardware wise? Also I will try this and see if it will work and will let you know how the results will be.

**Comment by ndeadly** [comment] 2022-02-23 06:31
> Is there anything that can be done hardware wise? 

No. The issue is the console sending a special bluetooth command that only exists for broadcom chipsets. Other chips that don't support it get disconnected if I allow the console to send it. I'm not sure whether it's the controller itself disconnecting or the switch disconnecting it when it doesn't receive the expected response, but in the end it doesn't really matter. I used to block this command for all third party controllers, but people started complaining about it killing their wifi performance when using DS4 controllers. The official ones support the command so it makes sense to allow it, but from the Switch's point of view we can't tell the 3rd party ones apart so you have to manually flag them. 

> Also do I make a folder with the command or is it a specific file I need to do?

You find the folder under `/config/MissionControl/controllers/` that matches the mac address of your controller and create an empty file titled `settsi_disable.flag` in there. You can use my [btdb](https://github.com/ndeadly/MissionControl/files/7227157/btdb-1300.zip) homebrew to list the paired devices on your console and find the mac address.

**Comment by Webhead2130** [comment] 2022-02-23 07:39
Oh, okay that makes sense. How do I create the empty file on windows? I’m still kinda new to modding so I’m not sure how it’s done

**Comment by Webhead2130** [comment] 2022-02-23 08:41
Actually never mind. I think I got it now. I’ll try it out and see if that works

**Comment by Masamune3210** [comment] 2022-02-23 20:16
Just make a txt file with nothing in it, and then change the name and extension to whatever

**Comment by Webhead2130** [comment] 2022-02-24 00:21
Okay, thanks!

**Comment by ndeadly** [comment] 2022-02-24 01:01
> Just make a txt file with nothing in it, and then change the name and extension to whatever

To add to this, make sure you have `File name extensions` checked in the view tab of windows explorer. Otherwise you won't change the file extension and will end up with a file named `settsi_disable.flag.txt`

**Comment by Webhead2130** [comment] 2022-02-24 02:34
I saw that when I first made the file. I’ll fix that then

**Comment by Webhead2130** [comment] 2022-02-25 05:31
So far I have been using it and it hasn’t been disconnecting but, it feels like the left stick is responding a bit slower than before

**Comment by ndeadly** [comment] 2022-02-25 06:14
It's possible. In blocking this command we are lying to the console that it's attempts to manage the wireless bandwidth usage are succeeding. Though I haven't noticed any problems with eg my Xbox controller, that also doesn't support the command.

Also, the controller state is all sent at once in a single packet, so it shouldn't be possible to notice a delay on one stick and nothing else.

**Comment by Webhead2130** [comment] 2022-02-25 06:32
I’ve mainly been noticing it when like I play a shooting game or on the selection screen for Smash ultimate

**Comment by Webhead2130** [comment] 2022-02-25 06:35
I see now that it’s not responsive but more as it takes more push in order for it to do the action that I want it to. Like the dead zone has been increased

**Comment by ndeadly** [comment] 2022-02-25 06:42
Adding the flag file shouldn't have any effect on that. If you've used older versions of Mission Control you could try deleting the `spi_flash.bin` file found in your controller's folder where you put the flag file and see if that changes anything. It's possible you have less accurate stick calibration data in there.

**Comment by Webhead2130** [comment] 2022-02-25 06:47
Okay, I’ll try that

**Comment by Webhead2130** [comment] 2022-02-25 07:06
I believe that fixed it. Thanks for the help!

**Closed** 2022-02-25 07:14 UTC
