### ISSUE TITLE
[Controller Request]: could you please add support to bluetooth Moga XP5-X plus, thanks 

### ISSUE THREAD

**Issue by ahmedrashied** [ndeadly/MissionControl#478] opened 2022-05-28 16:41 UTC
### Controller Name

Moga XP5-X plus

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Model number: GP-TPU020BDABQ

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ahmedrashied** [comment] 2022-05-28 17:07
This is the controller website:  
https://www.powera.com/p/moga/moga-xp5-x-plus-bluetooth-controller-for-mobile-cloud-gaming-1510705-01/

**Comment by ndeadly** [comment] 2022-05-29 08:22
This is a duplicate of https://github.com/ndeadly/MissionControl/issues/50

This controller uses Bluetooth LE and can't be supported until that's working.

**Closed** 2022-05-29 08:22 UTC
Labels: controller request
