### ISSUE TITLE
[Bug Report]: Controller immediately disconnects.

### ISSUE THREAD

**Issue by Bungwr** [ndeadly/MissionControl#465] opened 2022-05-08 09:10 UTC
### Switch Firmware Version

11.0.1

### Atmosphère Version

1.3.2 (Latest)

### Mission Control Version

0.7.0 (Latest)

### Boot Method

Unsure

### Issue Description

Using a dualsense controller when in pair mode it kinda almost pairs but then disconnects. On switch side nothing happens.

### Additional Context

Tried 2 dualsenses and checked on other systems and they're working perfectly. I'm not sure if my frimware is the issue but maybe is. Reinstalled Mission control plenty of times. Deleted Controller folder on config. Done just about anything and I really don't know what the issue is still twt. Any help appreciated tysm<3

**Comment by Bungwr** [comment] 2022-05-08 11:47
Just tried dualshock4 and same issue.

**Comment by ndeadly** [comment] 2022-05-09 08:03
Try charging your controllers. I have had several similar reports lately and in most cases the issue has turned out to be low battery.

**Comment by Bungwr** [comment] 2022-05-10 05:07
> 

I don't think the battery is the issue. I tried 3 controllers. Tried charging them but it's the same issue. Do I need to update my firmware perhaps?

**Comment by ndeadly** [comment] 2022-05-10 05:20
It's worth a try. I always test my releases on the most recent firmware at the time. Although all firmwares should be supported, the further back you go the less thoroughly tested things are going to be for the current release. You're always better off keeping your firmware up to date anyway.

**Comment by reichembach** [comment] 2022-06-05 20:42
Same thing happening to me when connecting a Dualshock 4. After syncing, it shows as paired but immediately disconnects. Happens both docked and undocked on latest firmware/atmosphère/mission control. Booting through hekate>fusee.bin if it matters

**Comment by ndeadly** [comment] 2022-06-06 08:42
@reichembach and you've tried charging the controller?

**Comment by Bungwr** [comment] 2022-06-06 09:48
> @reichembach and you've tried charging the controller?

I don't think it's a battery issue.. (at least for my side) 
Temporary fix is using a older version of mission-control and seems fine now.

**Comment by ndeadly** [comment] 2022-06-06 19:34
There's no easy way to check at the moment, but your atmosphere version might hint and which version you have based on what can work with it.

**Comment by estgold** [comment] 2022-06-07 17:52
Same issue, same version, before updating Atmosphere, works fine. I will try update Switch firmware or downgrade mission controll version

**Comment by estgold** [comment] 2022-06-07 18:03
Kefir 646, manualy install Mission Control 0.6.4 from releases. Disconnection fixed

**Comment by reichembach** [comment] 2022-06-07 23:58
Tried 0.6.4 but it crashes atmosphère, probably cause that mission control version doesn't support latest firmware. Based on the previous comment though, that the controllers don't disconnect on 0.6.4, maybe it has something to do with the newly added motion support for those controllers?

**Comment by ndeadly** [comment] 2022-06-08 11:12
> Tried 0.6.4 but it crashes atmosphère, probably cause that mission control version doesn't support latest firmware.

Yes, you would need to downgrade Atmosphere to a lower version in order to use that version.

> Based on the previous comment though, that the controllers don't disconnect on 0.6.4, maybe it has something to do with the newly added motion support for those controllers?

This may be in part, because controllers weren't actually instructed to disconnect prior to 0.7.0. I made this change because the previous behaviour was to abort and crash the system if anything went wrong. The downside to this however, is that I don't get any debugging information when something _does_ go wrong. Based on a previous report I got, I suspect the issue has something to do with file operations. This may be related to the motion support as you say, as that adds additional file operations to load and store the motion controls calibration. What I don't understand though, is why I can't reproduce it with either of my DS4 controllers, or why it hasn't been reported for any other controllers supporting motion controls.

Here's a version I built that removes the disconnection code. If the same error triggers, it will now crash your console, but it will generate an error report that you can upload here for me to take a look at.

[MissionControl-0.7.0-ds4-disconnect-fix-4f5cb51.zip](https://github.com/ndeadly/MissionControl/files/8860957/MissionControl-0.7.0-ds4-disconnect-fix-4f5cb51.zip)

**Comment by reichembach** [comment] 2022-06-10 00:06
Sorry for the late reply, could only test right now. 
Tried the version you provided but the result is the same, pairs and instantly disconnects. Also didn't crash, which I assumed it would based on this
> If the same error triggers, it will now crash your console, but it will generate an error report that you can upload here for me to take a look at.

**Comment by ndeadly** [comment] 2022-06-10 06:17
If this is the case, then it must be getting disconnected by Nintendo's code in your case. Try following the instructions here https://github.com/ndeadly/MissionControl/issues/342#issuecomment-954172676 and see if it helps.

**Comment by reichembach** [comment] 2022-06-10 21:09
There were no controller profiles to put the flag in, but I tested it again a few hours later and it didn't disconnect anymore! I have no idea why it suddenly started working, but I'll take it lol

**Comment by ndeadly** [comment] 2022-06-28 21:12
@Bungwr could this be the same problem you've been having? https://github.com/ndeadly/MissionControl/issues/488#issuecomment-1169120107

**Comment by Bungwr** [comment] 2022-06-28 21:30
> @Bungwr could this be the same problem you've been having? [#488 (comment)](https://github.com/ndeadly/MissionControl/issues/488#issuecomment-1169120107)

Hi ty for mentioning me for this. I don't think it is the same issue as my controllers r updated and it have the same issue on a ds4. For now I'm using an older version which works perfectly for me. Although I would like the motion controls but I don't like it that much on a controller.

**Comment by mrsteyk** [comment] 2022-07-24 10:02
> Here's a version I built that removes the disconnection code. If the same error triggers, it will now crash your console, but it will generate an error report that you can upload here for me to take a look at.
> 
> [MissionControl-0.7.0-ds4-disconnect-fix-4f5cb51.zip](https://github.com/ndeadly/MissionControl/files/8860957/MissionControl-0.7.0-ds4-disconnect-fix-4f5cb51.zip)

weirdly enough I got a crash [report_016cbc44c.bin](https://files.catbox.moe/s4hi2c.bin)

**Comment by Fireboter** [comment] 2022-08-19 15:18
im having the same issues, did u solve it?

**Comment by 11701177** [comment] 2022-09-27 13:11
Is there an update on this? This seems to be an ongoing issue. I exeperience the same error

**Comment by Fireboter** [comment] 2022-09-27 13:55
> Is there an update on this? This seems to be an ongoing issue. I exeperience the same error

I did not, please tell me if u find a solution.

**Comment by 11701177** [comment] 2022-09-28 20:23
Hi ndeadly,

seems like the latest dev release fixed the issue. I was able to connect ps4 and ps5 controlers

**Comment by Fireboter** [comment] 2022-09-28 20:44
> Hi ndeadly,
> 
> seems like the latest dev release fixed the issue. I was able to connect ps4 and ps5 controlers

I'll try tomorrow, thanks a lot!

**Comment by Fireboter** [comment] 2022-09-30 21:35
It works, thank u so much!

**Comment by ndeadly** [comment] 2022-10-05 22:44
Since the recent posts indicate that the above dev build fixes the reported issues, I'll assume this issue has been resolved in one way or another. If there are still issues when running the [latest release](https://github.com/ndeadly/MissionControl/releases/tag/v0.7.1) then this issue can be re-opened.

**Closed by ndeadly** 2022-10-05 22:44 UTC
