### ISSUE TITLE
Mapping On Xbox One S Controller incorrect.

### ISSUE THREAD

**Issue by jazzverso** [ndeadly/MissionControl#91] opened 2020-09-18 06:13 UTC
PS4 Controller works great and all mappings were working properly. On the xbox controller there was nothing bound to the home button, the menu and share buttons were mapped the l and r and the left bumper was mapped to x and b was not bound.

**Comment by lip9571** [comment] 2020-09-18 07:31
make sure your Xbox controller firmware is up to date

**Comment by ndeadly** [comment] 2020-09-18 09:00
Duplicate of #4 #8 #14 #36  #38 #48 #64

**Closed by ndeadly** 2020-09-18 09:00 UTC
