### ISSUE TITLE
just doesnt work

### ISSUE THREAD

**Issue by Mechanical-jv** [ndeadly/MissionControl#81] opened 2020-09-15 20:28 UTC
i dont know what the problem is exactly, it just crashes and tells me that a report was made on fatal errors.

https://drive.google.com/file/d/1qw0ni41yRBI4pZ_VIwB8GrmeHhjZP3SO/view?usp=sharing

**Comment by ndeadly** [comment] 2020-09-15 20:36
Duplicate of #76

**Closed by ndeadly** 2020-09-15 20:36 UTC
