### ISSUE TITLE
Suggestion: override the pro controller icon with the real controller icon

### ISSUE THREAD

**Issue by MrKcyre** [ndeadly/MissionControl#80] opened 2020-09-15 16:52 UTC
It's only an idea, if possible with layered-fs or any form of mitm (i really don't know if it is), to override the pro controller icon with the real controller icon.

**Comment by ndeadly** [comment] 2020-09-15 17:00
Duplicate of #69

I don't think it's really doable, or at least not worth the time investment. There's no IPC to mitm and as far as I know layered-fs doesn't allow for selective replacement of an asset.

**Closed** 2020-09-15 20:57 UTC

**Comment by MrKcyre** [comment] 2020-09-16 01:20
Sorry by duplicate, i did not saw #69 before, i understand why it's not worth it.. thanks!
