### ISSUE TITLE
[Controller Request]: Sony DualShock3 (Playstation 3) Controller

### ISSUE THREAD

**Issue by eddan-mossen** [ndeadly/MissionControl#590] opened 2023-03-03 09:03 UTC
### Controller Name

Sony DualShock3 (Playstation 3) Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Sony CECHZC2E, N1158

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment] 2023-03-03 09:06
Duplicate of https://github.com/ndeadly/MissionControl/issues/7

**Closed by ndeadly** 2023-03-03 09:06 UTC
Labels: controller request
