### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by ziginc** [ndeadly/MissionControl#843] opened 2024-07-29 13:45 UTC
### Controller Name

Amazon luna

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

I can pair the luna controller to many Bluetooth device but not the switch ps5 controller works fine. I really love the feel of the luna controller and really wish there is a way to make it work on the switch.

**Comment by ndeadly** [comment] 2024-07-29 13:48
Duplicate of #582 

This controller uses Bluetooth LE, which is not currently supported by the release versions. It is however already supported and working in private. I have test builds available on my discord server.

**Closed by ndeadly** 2024-07-29 13:48 UTC
Labels: controller request
