### ISSUE TITLE
[Controller Request]: Xbox Series X/S not working

### ISSUE THREAD

**Issue by Franneitor** [ndeadly/MissionControl#416] opened 2021-12-25 20:26 UTC
### Controller Name

Xbox series X/S controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

no matter what you do the controller will not connect to the switch, i tried using the USB cable and the bluethooth but it did not work

**Comment by Masamune3210** [comment] 2021-12-26 06:41
Series X/S controllers will not work currently with Mission Control over Bluetooth as Bluetooth LE hasn't been researched and implemented yet

**Comment by ndeadly** [comment] 2021-12-26 21:06
Duplicate of https://github.com/ndeadly/MissionControl/issues/135

**Closed by ndeadly** 2021-12-26 21:06 UTC
Labels: controller request
