### ISSUE TITLE
[Controller Request]: Afterglow Wii U Pro Controller

### ISSUE THREAD

**Issue by Coz-0** [ndeadly/MissionControl#585] opened 2023-02-18 02:59 UTC
### Controller Name

Afterglow Wii U Pro Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [X] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

The  4 blue lights flash when sync button is pressed but the controller never pairs.

**Comment by ndeadly** [comment] 2023-02-21 10:19
Duplicate of #327

**Closed** 2023-02-21 10:20 UTC
Labels: controller request
