### ISSUE TITLE
Atmosphere crash when going into controller menu

### ISSUE THREAD

**Issue by Eds1989** [ndeadly/MissionControl#54] opened 2020-09-07 14:24 UTC
Hi,

I'm getting an Atmosphere crash when trying to get into the controller menu to try this out.

Error code: 2144-0001 (0x290)
Program: 0100000000001000
Firmware: 10.1.0 (Atmosphere 0.14.1-master)

Going to assume a compatibility problem with some other sysmodule I have installed?

**Comment by ndeadly** [comment] 2020-09-07 15:03
Never heard of MissionControl causing this before. `0100000000001000` is qlaunch so it's at least not directly related. I don't think anything system components I touch even get called until you actually enter the screen and attempt to pair a controller.

I would guess you might be right and it's caused by something else since you're the first to complain of it. What else do you have installed?

**Comment by Eds1989** [comment] 2020-09-07 15:34
Sadly, I have quite a lot of other bits and pieces installed, so narrowing it down is quite the task;
NX-OvlLoader
SaltyNX
Emuiibo
Fizeau
ldn_mitm
ReverseNX
sys-clk
sys-con
sys-ftpd-light
sys-tune

I've also got a theme installed so believe there are some patches applied by this, as well as sigpatches

Think that's everything.

**Comment by ndeadly** [comment] 2020-09-07 15:45
Yeah, ok, given the number of things you have running I'd say chances of it being something else are pretty high. I think I'd start by disabling the theme and go from there. 

Could it even be just coincidence that you got the error after installing MissionControl? Does the crash occur every time you try to enter the controller applet?

**Comment by Eds1989** [comment] 2020-09-07 16:18
I'd agree it's one of those other things. My suspicion is it's most likely ldn_mitim, as that has given me a lot of trouble in the past causing crashes in other areas of Atmosphere.
Can confirm however, this particular crash does not occur after removing MissionControl.

If I can find the time (an inclination) to try going through and disabling/removing other bits, I'll report back my findings.

**Comment by Eds1989** [comment] 2020-09-11 18:59
Almost certainly looks to be compatibility with ldn_mitm_v1.5.0
As soon as I remove this, MissionControl works fine!

**Comment by ndeadly** [comment] 2020-09-12 08:42
Interesting. Good to know you got it working though. I'm going to close this issue since I think the problem is not with MissionControl. Will reopen if others start complaining of similar.

**Closed by ndeadly** 2020-09-12 08:42 UTC

**Comment by code-X-HQM** [comment] 2024-07-20 06:38
I have same problem after missioncontroll
