### ISSUE TITLE
Request: Support SX OS

### ISSUE THREAD

**Issue by Neanderthaliano** [ndeadly/MissionControl#96] opened 2020-09-22 12:15 UTC
Hi, Would you please make it run on SX OS? Thanks in advance.

**Comment by ndeadly** [comment] 2020-09-22 12:19
https://github.com/ndeadly/MissionControl#frequently-asked-questions

Duplicate of #23 #25 #32 #37 #41 #46 #82 #96

**Closed by ndeadly** 2020-09-22 12:19 UTC
