### ISSUE TITLE
Black screen in games after using MissionControl

### ISSUE THREAD

**Issue by HaxSam** [ndeadly/MissionControl#196] opened 2021-02-16 09:06 UTC
If I have MissionControl activated I only get blackscreen in the games and Linkalho only crashes if it also affects other homebrew apps I don't know.
Atmosphere: 0.18.0
MissionControl: 0.4.1

**Comment by ndeadly** [comment] 2021-02-16 09:14
What do you mean by black screen? Is it blank or do you see an error message? Has the console crashed or can you back out to the home menu?

I am also running these versions without any issues, and I assume by now so are many other users. I suspect this issue is probably caused by something else you have installed on your system. Can you show me the contents of your `atmosphere/contents` folder?

**Comment by jacoghi** [comment] 2021-02-18 04:08
I confirm @ndeadly's statement, AMS 0.18.x has created a lot of issues to many modules that were using the sm extensions, however, mission control is NOT one of them. I've been using it without any issues, and it behaves as it did before 0.18.x.

**Comment by HaxSam** [comment] 2021-02-18 17:20
I am not seeing any error message its a blank screen. One time everyting that i start crash everything when i start a game or open setting its always crashing after i deleted MissionControl evryting was fine.

Here its my contents hope u can help me.
[content.txt](https://github.com/ndeadly/MissionControl/files/6004649/content.txt)

But from my stand I seems the problem comming from MissionControl.
I will downloaded again an try to post the logs when I get a crash

**Comment by HaxSam** [comment] 2021-02-18 17:31
This time nothing crashed but i get problems in the games:
Super Mario 3D World + Bowsers Fury
Blazing Beaks

After the controller select the screen go black and get stuck.
How I can provide you with information that you can find the issue.

Also this probem show up after I installed MissionControl again.

**Comment by ndeadly** [comment] 2021-02-18 17:39
You have a **lot** of things installed to that directory. I wouldn't be surprised at all if this was resource exhaustion from running too many sysmodules. I can count at least 10 of them. It is likely MissionControl is just the one pushing you over the limit.

```
00FF0000636C6BFF	sys-clk
00FF0000A53BB665	SysDVR
0100000000000352	emuiibo
0100000000000464	SwitchPresence
420000000000000E	sys-ftpd
4200000000000010	ldn-mitm
420000000007E51A	tesla
430000000000000B	sys-botbase
43000000000000FF	nxsh
690000000000000D	sys-con
```
I imagine your problem will probably be resolved by disabling/deleting some of those that you don't use regularly. The other thing to look out for is that some sysmodules will require an update for Atmosphere 0.18.0. In particularly emuiibo and ldn-mitm often cause issues after an Atmosphere update.

**Comment by HaxSam** [comment] 2021-02-18 18:07
From the sysmodules I only activated
```
Tesla
sys-con
SysDVR
```

But I clean my content folder up and try it again

**Comment by HaxSam** [comment] 2021-02-18 18:35
It doesn't work.
I removed the most of the sysmodules and cleaned up my contents folder.
[contents.txt](https://github.com/ndeadly/MissionControl/files/6005023/contents.txt)

sysmodules
- [x] sys-con
- [ ] sys-clk
- [ ] sys-ftpd-light
- [x] Tesla
- [x] SysDVR
- [x] sys-botbase

**Comment by ndeadly** [comment] 2021-02-18 18:57
That's a big improvement but you still have a handful of things in there, some of which I'm not sure what they are. I don't know if you're using a tesla overlay or something to toggle the sysmodules on/off but that checklist you posted doesn't show all the sysmodules you've shown in the title ID list. ldn-mitm is still present for example.

My suggestion is that you move or rename the `contents` folder, do a fresh install of Atmosphere to put back the bare minimum title folders, and then add back the modules you want one-by-one, rebooting and testing in between. You can copy the folders from your original `contents` folder if you like, but it would be better to download each module again from github, to make sure you're using the most up-to-date release for each.  I am almost certain that if you start with just Mission Control, you will not see these black screens.

**Comment by HaxSam** [comment] 2021-02-18 19:05
That it what it did.
I deleted to many folders from my contenets folder so that atmosphere stop working.

I did a fresh install a new Version from Atmosphere and added the sysmodule that i know they work and i got the same problem after i added MissionControl.

Also the problem just comes when i have to select a controller in the game for example in Super Mario 3D World + Bowsers Fury after the selection the game freeze.

**Comment by ndeadly** [comment] 2021-02-18 19:23
Deleting folders until things stop working is not the same as removing the whole thing and starting over. All it takes is deleting one necessary atmosphere component and it will stop working. You can still have many problematic entries present.

It's not a matter of just adding back the modules you know work. They might all work in isolation, the issue is likely that you are running too many of them at once and exhausting some particular resource. This is why you need to put them back one by one to find where the limit gets crossed. If you start with Mission Control only you should see that it doesn't cause the issue by itself.

Additionally, you have several other things present (presumably title overrides) that could also be messing with the system.
```
0000000000000000
0100000000001000
0100000000001007
0100000000001013
```
`0100000000001007` sounds particularly suspicious, as this is the `playerSelect` applet

**Comment by HaxSam** [comment] 2021-02-18 19:42
Thank u for the help.
I found out the problem caused  from `ldn-mitm` but with a weird behavior without MissionControl everything work normaly.

Also i dont meant the `playerSelect` I meant where you add the controller to the game after this the game freeze.
![2021021820303800](https://user-images.githubusercontent.com/56654878/108412055-a311a400-7229-11eb-9e72-a04e9f764096.jpg)

**Comment by ndeadly** [comment] 2021-02-18 20:37
Yeah,` ldn-mitm` would have been one of my top suspects. Though I'm still surprised it's not just the number of modules you had running. I'm still not quite sure how Mission Control ends up getting dragged into this though.

> Also i dont meant the `playerSelect` I meant where you add the controller to the game after this the game freeze.
> ![2021021820303800](https://user-images.githubusercontent.com/56654878/108412055-a311a400-7229-11eb-9e72-a04e9f764096.jpg)

I'm pretty sure that _is_ the `playerSelect` applet.

**Closed by ndeadly** 2021-02-18 20:37 UTC
