### ISSUE TITLE
Ps4 controller issue

### ISSUE THREAD

**Issue by dimabbox** [ndeadly/MissionControl#336] opened 2021-08-23 05:48 UTC
Hey! When I try to connect ps4 controller , my switch immediately reboot and I just can reboot it again

**Comment by ndeadly** [comment] 2021-08-23 08:42
Could you tell me which firmware/Atmosphere/mission control versions you're running?

Is there an error message displayed or any error report generated? If you're running the latest version of mission control (0.5.1) this may be related to the new virtual spi flash feature. I saw a few crashes like this during development when something to do with file IO fails. Maybe I missed something. Does the reboot happen every time? Did it start happening after you did something in particular?

**Comment by YunoGasai67** [comment] 2021-09-03 02:42
Can confirm the switch crashes on latest Atmos with 12.0.3 firmware using dualshock

**Comment by Kronos2308** [comment] 2021-09-06 15:19
yes  is true

**Comment by Kronos2308** [comment] 2021-09-06 15:26
you forgot to make that mission controll make the contoller folder @ndeadly

**Comment by ndeadly** [comment] 2021-09-06 15:52
@Kronos2308 not sure what you're talking about. The `/config/MissionControl/controllers` directory is created by the makefile and will be present if you install correctly by copying the entire .zip contents to the root of your SD card. https://github.com/ndeadly/MissionControl/blob/5abe5f072820438ef7d3fedbbaa7451138888918/Makefile#L40

The individual controller directories are checked for and created if they don't exist here https://github.com/ndeadly/MissionControl/blob/5abe5f072820438ef7d3fedbbaa7451138888918/mc_mitm/source/controllers/emulated_switch_controller.cpp#L154-L161

**Comment by Kronos2308** [comment] 2021-09-06 16:01
if the config/MissionControl/controllers folder is deleted for any reason the app hang the entire console on controller pair 
try your self

**Comment by Kronos2308** [comment] 2021-09-06 16:05
in c just use 
mkdir(config,0777);
mkdir(config/MissionControl,0777);
mkdir(config/MissionControl/controllers,0777);
 or  fmkdir i not remember well

**Comment by Kronos2308** [comment] 2021-09-06 16:41
before create the .../controllers/``controlid``
.../controllers needs to be created

**Comment by ndeadly** [comment] 2021-09-06 17:21
> if the config/MissionControl/controllers folder is deleted for any reason the app hang the entire console on controller pair
> try your self

Ok, yeah that will happen. I guess I should probably handle that case.

**Comment by ndeadly** [comment] 2021-09-06 19:33
@Kronos2308 fixed here https://github.com/ndeadly/MissionControl/commit/5102fb21e4bb2f54e7fc0de5d2b6f166639a812a

@dimabbox, @YunoGasai67 are you still having issues with crashes? Could a missing `/config/MissionControl/controllers` directory be the cause of your issues?

**Comment by dimabbox** [comment] 2021-09-07 05:18
> @Kronos2308 fixed here https://github.com/ndeadly/MissionControl/commit/5102fb21e4bb2f54e7fc0de5d2b6f166639a812a
> 
> 
> 
> @dimabbox, @YunoGasai67 are you still having issues with crashes? Could a missing `/config/MissionControl/controllers` directory be the cause of your issues?

Yes, sir

**Comment by ndeadly** [comment] 2021-09-07 11:09
> > @Kronos2308 fixed here [5102fb2](https://github.com/ndeadly/MissionControl/commit/5102fb21e4bb2f54e7fc0de5d2b6f166639a812a)
> > @dimabbox, @YunoGasai67 are you still having issues with crashes? Could a missing `/config/MissionControl/controllers` directory be the cause of your issues?
> 
> Yes, sir

Yes you're still having crashes? Or yes this is the cause of your issue?

**Comment by Kronos2308** [comment] 2021-09-07 15:53
i think is the second 
he describe my error
becouse y download the realease with a app and the app not copy emty folders

**Comment by ndeadly** [comment] 2021-09-07 16:39
@Kronos2308 I wouldn't make any assumptions. All the user described was that the console crashes upon connecting a controller. This could be caused by any kind of unhandled file IO error, not just a missing directory.

> becouse y download the realease with a app and the app not copy empty folders
Which app is doing this?

**Comment by Kronos2308** [comment] 2021-09-07 16:47
one app i am programing was a mistake for my part thats wy i see the issue

**Comment by BonScott84** [comment] 2021-09-20 12:16
Hello,
same issue here, if i try to pair ds4, i got black screen and then i have to reboot the console

**Comment by BonScott84** [comment] 2021-09-20 14:01
ohhh i mmmm sooooo sorrry!!!! it was in the wrong path!!! moved the directory now is working :D sorry again and thank you

**Comment by ndeadly** [comment] 2021-11-01 21:05
Closing as this is fixed in the latest releases

**Closed by ndeadly** 2021-11-01 21:05 UTC
