### ISSUE TITLE
[Controller Request]: 8bitdo Ultimate 2C Android Bluetooth mode

### ISSUE THREAD

**Issue by CoughfeeMug** [ndeadly/MissionControl#877] opened 2024-10-23 16:10 UTC
### Controller Name

8bitdo Ultimate 2C

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment] 2024-10-27 11:17
Duplicate of #851

**Closed by ndeadly** 2024-10-27 11:17 UTC
Labels: controller request
