### ISSUE TITLE
petition for xbox series s/x support

### ISSUE THREAD

**Issue by ivaburug1** [ndeadly/MissionControl#745] opened 2023-11-02 19:38 UTC
### Controller Name

xbox series s/x controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment] 2023-11-02 19:41
Duplicate of https://github.com/ndeadly/MissionControl/issues/135

**Closed by ndeadly** 2023-11-02 19:41 UTC
Labels: controller request
