### ISSUE TITLE
Vibration is delegated to switch console from Dualshock 4 controller

### ISSUE THREAD

**Issue by victorlev01** [ndeadly/MissionControl#138] opened 2020-11-14 18:47 UTC
Hello, downloaded (0.3.0) latest version of MC. Used Playstation dualshock 4 controller.
After connecting if vibration is enabled - it works on switch(with joycons connected) and not dualshock controller.
If it can be always disabled it will be better, before its implemented,
other is great, thanks!

**Comment by ndeadly** [comment] 2020-11-14 19:39
Am I understanding correctly that when you connect and play with the dualshock controller the joycons connected to the console vibrate instead?

How can this issue be reproduced? Are you experiencing it playing 3D All-Stars by any chance? I had a user complain of a similar sounding issue with this game a while ago (sorry can't seem to find where it was reported), but as far as I could tell it was a bug (or feature) of the game itself and it happened with or without MissionControl installed. I was able to reproduce it using a Switch Pro Controller. If you can show me proof that it's only happening with MC installed I'll gladly look into it.

**Comment by victorlev01** [comment] 2020-11-24 04:33
It can be reproduced when switch is not in docked mode, a dont remember what game i played, i think it was super mario Bros U deluxe, or smash ultimate.
Also some after some time it seems controller right button is stuck, like i press it all time, it fixes by resetting controllers config.
I use only 3 external Dualshock 4 original controllers with switch.

**Comment by ndeadly** [comment] 2020-11-24 10:13
You're going to have to be more specific if you want help with this. I need to know exactly which game(s) it happens with, the steps required to trigger the issue and any other information that might be helpful eg. OFW version, game version, other sysmodules you have running.

Likewise with the controller button sticking. Though it might be better to open a separate issue report for that.

**Comment by vonis22** [comment] 2022-01-13 21:11
I’d like of you could take another look at this. Im playing pokemon Shining Pearl and the switch console is vibrating instead of the dualshock 4. Docked or undocked doesnt matter.

Is there any more info you require?

**Comment by ndeadly** [comment] 2022-01-14 00:20
@vonis22 can you verify whether the console vibrates using a wireless controller _**without**_ Mission Control installed? In 3d All-stars I was able to observe this behaviour when Mission Control wasn't even active, suggesting it was an issue with the game itself. I don't even know how vibrations _could_ be erroneously sent to the console seeing as it's not even the same commands used for non-bluetooth connections...

If you're convinced this only happens with Mission Control running, let me know the exact steps I can follow to reproduce the issue.

**Comment by vonis22** [comment] 2022-01-14 14:54
I rebooted Pokemon today, and suddenly the issue is gone. I've checked in the settings by toggling vibration on and off. The ds4 now vibrates when I toggle, the intensity is very low though. Guess that's another issue, sorry to bother re-opening this one.

**Closed** 2022-10-10 14:43 UTC
