### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by Leohw5** [ndeadly/MissionControl#809] opened 2024-04-28 10:01 UTC
### Controller Name

Xbox Series

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment] 2024-04-30 08:47
Duplicate of #135

**Closed by ndeadly** 2024-04-30 08:47 UTC
Labels: controller request
