### ISSUE TITLE
Freezing on switch logo

### ISSUE THREAD

**Issue by YusefFaruq** [ndeadly/MissionControl#61] opened 2020-09-10 10:44 UTC
Sorry if I'm missing something obvious.
Hello, I am on firmware 9.0.1 and atmosphere version 0.14.2
I downloaded the MissionControl files and then I copied them to the root of my sd card, merged and rebooted my switch back to emummc atmosphere. It reboots fine all the way to the switch logo and then freezes indefinitely.
I can't go past this step.
I'm not sure where I went wrong. I've tried installing atmosphere, copying the files again, and rebooting again, but I still get the same problem. 
Could you please help me out?
Thank you.

**Comment by ndeadly** [comment] 2020-09-10 10:46
Duplicate of #56

**Closed by ndeadly** 2020-09-10 10:46 UTC
