### ISSUE TITLE
[Bug Report]: dualshock 4 touchpad registering as - button

### ISSUE THREAD

**Issue by crosby93987** [ndeadly/MissionControl#708] opened 2023-08-27 04:58 UTC
### Switch Firmware Version

16.1.0 (Latest)

### Atmosphère Version

1.5.5 (Latest)

### Mission Control Version

0.9.3 (Latest)

### Boot Method

Hekate

### Issue Description

its pretty much all in the title. the touchpad is the - button. if i remap the - button (which is usually the share button) it also remaps the touchpad. also the touchpad sometimes just does nothing (have to press multiple times for it to do anything). at first i thought it was a controller issue but this issue persisted when trying with my other dualshock 4 controllers. this wasnt an issue on the previous version of mission control, the touchpad worked just fine all the time. idk if this is relevant or not but this issue is not present on the dualsense whatsoever. so yeah thats pretty much it. attached is a picture of my dog for your troubles. have a good day bro (brofist like pewdiepie)
![pepper](https://github.com/ndeadly/MissionControl/assets/138307499/788e9c43-3f2b-476f-b306-2dd5d31ac8e6)

**Comment by ndeadly** [comment] 2023-08-27 12:45
From the release notes changelog:

> - Changed behaviour of Dualshock 4/Dualsense touchpad so that the outer edges are mapped to +/- in order to prevent accidental screenshots being taken when pressing those buttons

This is a change introduced in the latest version. It should only apply to the edges of the touchpad, the center should still map to capture.

> idk if this is relevant or not but this issue is not present on the dualsense whatsoever

The feature should be applied in the same way to the dualsense. When I tested this it was working as intended for both controllers. Is this not the case?

**Comment by crosby93987** [comment] 2023-08-27 16:19
oh damn alright my bad for not reading the changes. that being said theres still a bunch of issues with the touchpad so i made a video (on youtube bc file size was too big for here) showing them to you! feel free to ask if theres any more question. 
also in the video i said the switch makes a noise when i press the touchpad (- outer edge in this case but also does this with +) and the input cant be done (like when youre in a menu where pressing +/- again does nothing) and in that specific clip the noise only registered every few button presses (meaning the input wasnt registering everytime) this isnt consistent and sometimes the touchpad inputs are always registered. no idea what causes this. only clarifying cuz i didnt really explain that in the clip. also not a native english speaker lol so sorry if my english is rough. anyways have a nice day bro(fist like pewdiepie)


https://www.youtube.com/watch?v=9DWSF0dT0j8

**Comment by crosby93987** [comment] 2023-08-28 18:01
i was gonna take a screenshot with my joycons instead just now, but it seems like after the first screenshot attempt (shown in the video on my previous comment) the screenshot function is completely disabled on all controllers until the dualshock/dualsense gets unpaired. sorry to bother you with this btw

**Comment by ndeadly** [comment] 2023-08-28 18:58
Hey, sorry it's taken a while to respond - I'm always getting tugged at in multiple directions around the time of a new release. Too many issues, not enough time...

I watched your video yesterday, and was able to confirm that there is indeed some weirdness in the controller behaviour, though yours seemed worse than mine. What's very strange is that I tested all of this, and even shared it in another issue for others to test before I committed the code and everything was working fine. I will try to take a look into it in the next few days.

**Comment by crosby93987** [comment] 2023-08-28 19:18
its all good man no problems. i appreciate all the work you do and i hope you have a good day! :)

**Comment by crosby93987** [comment] 2023-08-30 17:25
my asshole piece of shit friend keeps bothering me about this even though i already said the screenshot function doesnt work after the first screenshot, but the dpad up + minus button doesnt work either. sorry to bother you with this but i want that friend to shut up because hes fucking DUMB and STUPID

**Comment by fkyyt** [comment] 2023-09-05 06:45
触摸板变成了3个键，减号-，加号+，录屏。休眠再唤醒才可以再次录屏，但是截图功能从一开始就是失效的。

**Comment by Catalina0796** [comment] 2023-10-01 02:48
What's the solution to the share button not working? I tried to change it but it doesnt work either, you just lose the - button. I can only take videos with the touch pad, but not always. Any solution?

**Comment by fkyyt** [comment] 2023-10-01 03:04
退回全部版本，
Returned Version，
don't use AMS16.1.0+Atmosphere1.5.5+MissonControl_0.9.3

use
16.0.3+1.5.4+0.9.2



---- Replied Message ----
| From | ***@***.***> |
| Date | 10/01/2023 10:49 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [ndeadly/MissionControl] [Bug Report]: dualshock 4 touchpad registering as - button (Issue #708) |

What's the solution to the share button not working? I tried to change it but it doesnt work either, you just lose the - button. I can only take videos with the touch pad, but not always. Any solution?

**Comment by ndeadly** [comment] 2023-10-13 16:26
The issue with the DS4 capture button should be resolved in the latest release

**Closed by ndeadly** 2023-10-13 16:26 UTC
Labels: bug
