### ISSUE TITLE
[Controller Request]: Xbox Series X|S Controller Support

### ISSUE THREAD

**Issue by z3ngy11** [ndeadly/MissionControl#830] opened 2024-06-17 03:38 UTC
### Controller Name

Xbox Series X|S Controller

### Current Controller Behaviour

Other (please specify below)

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Can you please make the Xbox Series X|S Controller be supported in this mod. I can't find any other mods that do support it. Also I really don't want to buy an adapter so please try add support to the controller.

Thanks

**Comment by ndeadly** [comment] 2024-06-17 12:22
Duplicate of #135

**Closed by ndeadly** 2024-06-17 12:22 UTC
Labels: controller request
