### ISSUE TITLE
[Bug Report]: Moga Pro Power previously working, now not

### ISSUE THREAD

**Issue by dimka4996** [ndeadly/MissionControl#415] opened 2021-12-25 07:49 UTC
### Switch Firmware Version

13.2.0 (Latest)

### Atmosphère Version

1.2.5 (Latest)

### Mission Control Version

0.6.3 (Latest)

### Boot Method

Fusée

### Issue Description

I used previously Moga Pro Power 2 with NS via mission control, now controller cyclically reconnecting, for few seconds appears in controllers and disconnects.

**Comment by ndeadly** [comment] 2021-12-25 20:06
This is a duplicate of https://github.com/ndeadly/MissionControl/issues/408

You can find a working build for the moga controllers in the comments https://github.com/ndeadly/MissionControl/issues/408#issuecomment-992585265

**Closed by ndeadly** 2021-12-25 20:06 UTC
