### ISSUE TITLE
[Controller Request]: Google Stadia

### ISSUE THREAD

**Issue by kalenderfamily** [ndeadly/MissionControl#800] opened 2024-04-03 16:06 UTC
### Controller Name

Google Stadia

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

After crashed I updatet to 1.7.0 pre release and now Switch boots up.

Tried to connect Google Stadia but unsuccessful :-(

**Comment by ndeadly** [comment] 2024-04-03 20:54
Duplicate of [#568](https://github.com/ndeadly/MissionControl/issues/568)

**Closed by ndeadly** 2024-04-03 20:54 UTC
Labels: controller request

**Comment by pmnlla** [comment] 2024-04-04 01:41
My brother in christ this is literally a pinned issue

**Comment by impeeza** [comment] 2024-04-04 05:05
The problem is Stadia new firmware is only BLE (even if the controller have WiFi, Bluetooth 5 and BLE hardware) and Mission Controll do not support BLE (yet)
