### ISSUE TITLE
Crash on boot/reboot

### ISSUE THREAD

**Issue by Lagmobile** [ndeadly/MissionControl#60] opened 2020-09-10 07:43 UTC
Left a comment on the wololo page but this seems like a better place for a bug report.

Getting a crash on boot on atmosphere 14.2

Thought it was a corrupt file during the fttp transfer but plugging it into my PC it still crashes with the latest atmosphere.

Through fttp and reboot it went straight into an error screen after the atmosphere splash and endlessly loops attempting to reboot.

On PC it hangs on the Switch startup splash and just stays there indefinitely.

Reinstalling atmosphere 14.2 solved both issues

**Comment by ndeadly** [comment] 2020-09-10 07:46
Duplicate of #56

**Closed** 2020-09-10 07:46 UTC
Labels: duplicate
