### ISSUE TITLE
Xbox Series Elite 2 Controller doesnt work

### ISSUE THREAD

**Issue by EliasKrug** [ndeadly/MissionControl#421] opened 2022-01-11 13:39 UTC
### Switch Firmware Version

13.2.0 (Latest)

### Atmosphère Version

1.2.5 (Latest)

### Mission Control Version

0.6.3 (Latest)

### Boot Method

Hekate

### Issue Description

The Switch cant detect the controller even tho its in pairing mode, some guy on youtube had the same problem and couldnt fix it either.

**Comment by ndeadly** [comment] 2022-01-11 13:52
Which firmware version is your controller on? If you have updated recently you are likely on the new version that converts Xbox controllers to use Bluetooth LE, which is not supported.

Someone on gbatemp encountered this scenario recently https://gbatemp.net/threads/missioncontrol-use-controllers-from-other-consoles-natively-via-bluetooth.572645/post-9705971

**Comment by EliasKrug** [comment] 2022-01-11 13:56
I bought it in November and never updated it but this should be the issue, ill try to downgrade the firmware. Thank you!!!

**Comment by EliasKrug** [comment] 2022-01-11 13:59
Ok, no i cant because an xbox is needed in order to downgrade

**Comment by ndeadly** [comment] 2022-01-12 01:44
Closing under the assumption that the controller firmware is the issue. The solution is to either downgrade using an Xbox console, or wait until Bluetooth LE is supported.

If you have reason to believe the problem is caused by something else, feel free to re-open

**Closed by ndeadly** 2022-01-12 01:44 UTC
