### ISSUE TITLE
Not working on latest atmosphere + HOS 12.1.0

### ISSUE THREAD

**Issue by OsoaGitHub** [ndeadly/MissionControl#308] opened 2021-07-06 19:37 UTC
Just gives a bland screen on boot

**Comment by ndeadly** [comment] 2021-07-06 20:17
Works fine for me. Are you sure you installed the [latest version](https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.4)? (It's not the one that shows up as latest on the main page)

**Comment by OsoaGitHub** [comment] 2021-07-06 20:27
> 
> 
> Works fine for me. Are you sure you installed the [latest version](https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-alpha.4)? (It's not the one that shows up as latest on the main page)

yup, latest version

**Comment by Theguysayhi** [comment] 2021-07-06 20:48
I can confirm I'm also having the same issue.

**Comment by ndeadly** [comment] 2021-07-06 21:18
Are you sure the issue is caused by Mission Control? Can you tell me more about your environment, confirming version numbers instead of just stating "latest"? Do you boot with hekate or fusee primary? Which other custom sysmodules do you have installed?

**Comment by OsoaGitHub** [comment] 2021-07-06 21:22
I boot with fusee, I have atmosphere 0.19.5 on HOS 12.1.0. The only other sysmodules I have is sys-clk, tesla and nx-ovlloader. I will try deleting my atmosphere folder tomorrow but it's late right now

**Comment by ndeadly** [comment] 2021-07-06 21:25
And Mission Control version?

**Comment by OsoaGitHub** [comment] 2021-07-06 21:27
MissionControl 0.5.0 pre-release 4, I've tried reinstalling it, I'm certain I'm using this version

**Comment by ndeadly** [comment] 2021-07-06 21:35
Hmm ok, everything sounds fine. I've recompiled it with the latest commit to libstratosphere so you can try this build and see if it works. This really shouldn't be required anymore though...

[MissionControl-0.5.0-alpha.4-develop-ff2cb79.zip](https://github.com/ndeadly/MissionControl/files/6772918/MissionControl-0.5.0-alpha.4-develop-ff2cb79.zip)

**Comment by Theguysayhi** [comment] 2021-07-06 21:39
Just tested the build, and I can confirm it works on my version!

**Comment by ndeadly** [comment] 2021-07-06 22:20
I was able to reproduce the black screen attempting to boot with fusee-primary, so I can confirm this is real. It seems like a similar issue to what was seen (and fixed) after the previous atmosphere release where hekate boots succesfully due to misconfiguring the firmware version number, only this time it may be cause by a bump to the minor version instead of micro. I've mentioned it to SciresM and will wait to see what comes of it before deciding if _another_ pre-release version is necessary. For now anyone experiencing this issue can either boot with hekate or use the build from this thread.

**Comment by gusklein** [comment] 2021-07-07 04:23
for me the problem is associated with sigpatches.

**Comment by wanted8x** [comment] 2021-07-07 16:52
For me not worked on 12.1 amsPLUS 0.19.5. I Have already install alpha4. Not Working. 
i Install MissionControl-0.5.0-alpha.4-develop-ff2cb79.zip, but not working.

**Comment by ndeadly** [comment] 2021-07-07 17:03
> For me not worked on 12.1 amsPLUS 0.19.5. I Have already install alpha4. Not Working.
> i Install MissionControl-0.5.0-alpha.4-develop-ff2cb79.zip, but not working.

I can't provide support for third party atmosphere distributions.

**Comment by wanted8x** [comment] 2021-07-07 17:05
I mean: MissionControl does not working on latest atmosphere + HOS 12.1.0

**Comment by ndeadly** [comment] 2021-07-07 17:10
What do you mean by not working? Black screen? Error message? Controllers not connecting? The current pre-release should work when booted via hekate, but the build posted above has been tested and confirmed working with fusee too. If it doesn't work for you there must be something different about your setup.

**Comment by wanted8x** [comment] 2021-07-07 17:16
i have blackscreen. I booted via hekate, and the Controller Menu give me Error (Blue Screen). 
Always was working on 12.0.1 with amsPLUS 0.19.4
After amsPLUS update and firmware update, its crashes in Controller Menu.

**Comment by ndeadly** [comment] 2021-07-07 17:18
Post the error screen you get.

**Comment by wanted8x** [comment] 2021-07-07 17:22
I formatting my emuMMC now. Then i'll backup my emuMMC and install missioncontrol again. (MissionControl-0.5.0-alpha.4-develop-ff2cb79.zip)
I'll call back

But Error Code was 2144-0001 (0x290).

**Comment by wanted8x** [comment] 2021-07-07 17:35
It worked for me. 
I formatting emuMMC, and config all. than install MissionControl from HB appstore. than copied MissionControl-0.5.0-alpha.4-develop-ff2cb79.zip in to SD Kart. 
Maybe there was an error while updating.

Thanks

**Comment by C0nsp1racy** [comment] 2021-07-09 13:03
> Just tested the build, and I can confirm it works on my version!


As Feedback. same situation here. AMS 0.19.5 + HOS 12.1.0, Hekate 5.5.8 to chainload fusee-primary caused a bland screen on boot using only Mission Control MissionControl-0.5.0-alpha.4-develop-aa48059. Using MissionControl-0.5.0-alpha.4-develop-ff2cb79 from this thread solved the issue.

**Comment by ndeadly** [comment] 2021-07-09 13:19
Thanks for the feedback. By now it's more or less understood what's happening and the circumstances it happens under, just not the exact cause. The build here will work for everyone, I'm just not sure whether a new release is really the answer if the problem could be fixed within atmosphere. SciresM is willing to address it if it makes sense, but the lack of error message makes it hard to track down what's going wrong.

I guess I'll just make yet another pre-release for now to put an end to the confusion.

**Comment by OsoaGitHub** [comment] 2021-07-09 15:42
> 
> 
> Thanks for the feedback. By now it's more or less understood what's happening and the circumstances it happens under, just not the exact cause. The build here will work for everyone, I'm just not sure whether a new release is really the answer if the problem could be fixed within atmosphere. SciresM is willing to address it if it makes sense, but the lack of error message makes it hard to track down what's going wrong.
> 
> I guess I'll just make yet another pre-release for now to put an end to the confusion.

I'm assuming v0.5.0-beta is the pre-release you're refering to?

**Comment by ndeadly** [comment] 2021-07-09 15:45
> > Thanks for the feedback. By now it's more or less understood what's happening and the circumstances it happens under, just not the exact cause. The build here will work for everyone, I'm just not sure whether a new release is really the answer if the problem could be fixed within atmosphere. SciresM is willing to address it if it makes sense, but the lack of error message makes it hard to track down what's going wrong.
> > I guess I'll just make yet another pre-release for now to put an end to the confusion.
> 
> I'm assuming v0.5.0-beta is the pre-release you're refering to?

Ha yeah I forgot I pushed the tag. I was going to publish it earlier but thought I might try to squeeze in a couple of bugfixes after I finish work.

**Comment by ndeadly** [comment] 2021-07-09 18:21
Here you go. New beta release that will boot for everyone and incorporates a few bugfixes. Enjoy

https://github.com/ndeadly/MissionControl/releases/tag/v0.5.0-beta

**Closed by ndeadly** 2021-07-09 18:21 UTC

**Comment by OsoaGitHub** [comment] 2021-07-09 20:34
Working fine now, thanks

**Comment by C0nsp1racy** [comment] 2021-07-12 20:56
> Thanks for the feedback. By now it's more or less understood what's happening and the circumstances it happens under, just not the exact cause. The build here will work for everyone, I'm just not sure whether a new release is really the answer if the problem could be fixed within atmosphere. SciresM is willing to address it if it makes sense, but the lack of error message makes it hard to track down what's going wrong.
> 
> I guess I'll just make yet another pre-release for now to put an end to the confusion.

It does make a lot of sense tbh. Anything i can do the help?

**Comment by ndeadly** [comment] 2021-07-12 21:07
Probably not tbh. I'm not really sure how you'd debug a frozen boot short of compiling atmosphere or libstratosphere with abort calls thrown in at various points during the boot process to see how far along it makes it. Probably not worth your time seeing as I've now released 0.5.0 compiled with all the latest changes.

**Comment by C0nsp1racy** [comment] 2021-07-15 14:37
Alright! Fair enough. Thanks all the time and effort you put in the project, Mission Control is much appriciated by many.
