### ISSUE TITLE
[Bug Report]: 

### ISSUE THREAD

**Issue by DexterDoesStuff** [ndeadly/MissionControl#795] opened 2024-03-30 10:48 UTC
### Switch Firmware Version

Other (please specify in issue description)

### Atmosphère Version

Other (please specify in issue description)

### Mission Control Version

0.10.0 (Latest)

### Boot Method

Hekate

### Issue Description

Hekate 6.11
Atmosphere 1.7.0

I dont know why this is happening? could be cuz its outdated idk

### Error Report

Panic occured while running Atmosphere.
Title ID: 010000000000BD00
Error: std: abort (0xFFE)

### Additional Context

I used the official github page for MissionControl.

**Comment by gokuss1213** [comment] 2024-03-30 18:45
Same here. I guess the problem is firmware 18.0.0 so we need to wait for a mission control update. To temporarily fix the issue deleate mission control by deleating the folder "010000000000BD00" in atmosphere/contents

**Comment by ndeadly** [comment] 2024-03-31 03:46
Duplicate of #794

**Closed by ndeadly** 2024-03-31 03:46 UTC
