### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by Zacharybinx34** [ndeadly/MissionControl#406] opened 2021-12-06 04:46 UTC
### Feature Description

Would be nice to use controllers as joycons

### Rationale

Convenient.

**Comment by ndeadly** [comment] 2021-12-06 12:11
Duplicate of https://github.com/ndeadly/MissionControl/issues/108

I have spent some time looking into it, and it can definitely be done, but there are some issues that need to be resolved before anything is release ready.

**Closed by ndeadly** 2021-12-06 12:11 UTC
Labels: feature request
