### ISSUE TITLE
[Controller Request]: BTP-2585N2

### ISSUE THREAD

**Issue by tyowen** [ndeadly/MissionControl#665] opened 2023-06-17 17:58 UTC
### Controller Name

BTP-2585N2

### Current Controller Behaviour

Controller successfully pairs with the console and responds to inputs but control mapping is incorrect

### Controller vendor and product ID

20bc:5501

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Input Report Format

i have got the build from #620 and really enjoy and appreciate your work. however, there are two buttons missing, Left and Right joysticks pressing down

L joystick (press down) 03 00 0f 00 20 80 80 80 80 00 00 00
R joystick (press down) 03 00 0f 00 40 80 80 80 80 00 00 00

again really appreciate your work. if you could add those two buttons that would even more wonderful :D

**Comment by ndeadly** [comment] 2023-06-17 18:47
Duplicate of https://github.com/ndeadly/MissionControl/issues/620

**Closed** 2023-06-19 08:24 UTC
Labels: controller request

**Comment by tyowen** [comment] 2023-06-22 17:17
thank you so much!
