### ISSUE TITLE
[Controller Request]: Stadia controller

### ISSUE THREAD

**Issue by Percion** [ndeadly/MissionControl#867] opened 2024-09-30 18:53 UTC
### Controller Name

Stadia

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment] 2024-09-30 18:54
Duplicate of #568

**Closed** 2024-09-30 18:54 UTC
Labels: controller request
