### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by Xhiil** [ndeadly/MissionControl#555] opened 2022-12-23 05:35 UTC
### Controller Name

Series S/X controllers

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by Masamune3210** [comment] 2022-12-23 05:43
Please try to search for already existing issue reports first before making a new one. Series X/S controllers require Bluetooth LE, which is being worked on but is currently not ready

**Comment by ndeadly** [comment] 2022-12-23 08:18
Duplicate of #135

**Closed** 2022-12-23 08:19 UTC
Labels: controller request
