### ISSUE TITLE
SN30 Pro issue

### ISSUE THREAD

**Issue by thornos78** [ndeadly/MissionControl#320] opened 2021-07-21 21:06 UTC
Dude, congratulations for your great work, but I have a problem when I try to pair the 8Bitdo SN30 Pro controller this fails to pair, all other controllers work correctly XBOX, PS4, WIIU.

Regards

**Comment by impeeza** [comment] 2021-07-21 21:08
8 BitDO SN30 Pro, have a native Switch mode (pres Y+Start) and it emulates a Switch Pro controller, so MissionControl has nothing to do with that.

**Comment by thornos78** [comment] 2021-07-21 21:11
I was using the 8bitdo controller before updating the Nintendo Switch and putting mission control, but now the controller doesn't work, maybe it's a problem with the nintento update. I will remove mission control and try and see if that's it.

**Comment by thornos78** [comment] 2021-07-21 21:27
It doesn't work without Mission Control either, apparently Nintento has removed the compatibility... I close problem.

**Comment by impeeza** [comment] 2021-07-21 21:47
Mine works just fin with and without MissionControl,  try updating the SN30 Pro firmware mine is SN30_Pro+_Firmware_V5.02_Beta2.zip

**Comment by thornos78** [comment] 2021-07-21 21:50
I managed to solve it, I read in a forum that you had to connect the controller by cable to the dock of the switch, after that and paired by bluetooth without problems.

**Comment by jamjazz** [comment] 2021-08-03 19:43
Pairing 8bitdo SN30 Pro on switch by missioncontrol ... no problem for me with the last release of missioncontrol...
Just follow 8bitdo instructions for "switch" : 
- launch controlers synchro manager of "switch", and press start/Y simultaneously on 8bitdo 2 seconds ... leds are moving itself right/left,
and now : press the little sync button above the 8bitdo controler ... wait few seconds ... is paired !

**Comment by ndeadly** [comment] 2021-08-03 20:48
If you're using the latest release of mission control, I'd actually recommend you use the XInput mode of the controller. The latest release fixes an issue where the analog stick values max out too early due to incorrect/missing calibration data. Incidentally, this appears to be similar to an issue people have complained of to 8bitdo about their controllers. The fix will only work in XInput mode though, because Switch mode is indistinguishable from a real controller where we expect valid calibration data to be sent.

**Comment by thornos78** [comment] 2021-08-03 20:57
> If you're using the latest release of mission control, I'd actually recommend you use the XInput mode of the controller. The latest release fixes an issue where the analog stick values max out too early due to incorrect/missing calibration data. Incidentally, this appears to be similar to an issue people have complained of to 8bitdo about their controllers. The fix will only work in XInput mode though, because Switch mode is indistinguishable from a real controller where we expect valid calibration data to be sent. Switch mode will need to be fixed in the 8bitdo firmware.

Thanks for the tip, I'll change it when I get home. I did not know about that problem that 8bitdo had

**Comment by ndeadly** [comment] 2021-08-03 21:10
It's possible they've fixed it, but last I heard the issue was still present and people had been complaining of it for years. I don't own an 8bitdo controller myself so I can only go by what others have told me. You should be able to verify pretty easily using the analog stick calibration screen in the controller menu though.

**Comment by thornos78** [comment] 2021-08-04 00:43
> It's possible they've fixed it, but last I heard the issue was still present and people had been complaining of it for years. I don't own an 8bitdo controller myself so I can only go by what others have told me. You should be able to verify pretty easily using the analog stick calibration screen in the controller menu though.

I just tried it and the calibration looks good in the section you mentioned, in the same way I will be attentive in case it gets out of calibration.

**Comment by impeeza** [comment] 2021-08-04 22:00
Hi, I own a SN30 Pro+ since Firmware 4.0 It have 4 modes (selected on the turn on of controller):

Buttons - PID reported - Mode
X+Start (PID 045e:02e0) X-Input mode. (Simulates a Microsoft Xbox One S Controller)
A+Start (PID 054C:05C4) D-Input mode (Simulates a Sony, DualShock 4 controller
B+Start (PID 2DC8:6102) D-Input the «8BitDo -Android- native mode»
Y+Start (PID 057e:2009) Switch Pro Controller mode (Simulate a original Nintendo Switch Pro Controller)

When I start the controller on Switch mode obviously Mission Control do not intercept because the controller announce itself as 057e:2009. and because the controller firmware do not have the correct calibration data handle; the 100% of the switch reported axis are get when you move approx the 75% of the stick,  several people have reported the issue to 8BitDo, but I will not hold my breath, they support is almost nonexistent.

I just update my Switch to MissionControl-0.5.0-master-9547d51.zip, used BTDB to clean the pairing database, reboot the console and turn on the controller on X-Input mode it Pairs almost immediately and now BtDB shows a 045e:02e0 8BitDo SN 30 Pro+ paired, but on the calibrate sticks menu the 100% of axis is still get on the 75% of the stick ;( the difference now is the calibration procedure able to finish, when I try the calibration of SN 30 Pro+ on Switch mode, the wizard never ends and fail.

@ndeadly let me know how can I help to debug and test with my SN 30 Pro+.

regards from Colombia.

**Comment by thornos78** [comment] 2021-08-04 22:07
You are right about the maximum value, the problem persists in 8bitdo

**Comment by ndeadly** [comment] 2021-08-04 22:30
@impeeza oh the problem still persists? I'll admit that I was only speculating that it was resolved, but I still think it should be possible to solve the issue through the calibration data exchanged when the controller connects.

Here's the app I used to identify the original problem in Xbox One controllers. I think it should work for the 8bitdo in XInput mode without modification. It prints both the raw values coming from the controller, and the converted values as seen by the system in hex, decimal and as a normalised float between ±1. The most interesting values to check are the raw min/max hex values in x and y vs the corresponding normalised system values. My code for Xbox  controllers assumes the raw values vary between `0x0000` and `0xffff`. If they don't then that explains why the problem isn't fixed.
[xbox-analog-stick-test.zip](https://github.com/ndeadly/MissionControl/files/6934700/xbox-analog-stick-test.zip)

That's interesting about the calibration being able to complete now. Somebody informed my about it recently but I wasn't sure what made it start working. The fact that it fails in Switch mode suggests that maybe it has something to do with me now using valid calibration data for the emulated controllers. Does completing the calibration make the sticks behave correctly? (You shouldn't need to do this though if my fix is working)

**Comment by impeeza** [comment] 2021-08-04 23:01
Hi, @ndeadly I will try the test this night,  by now I can confirm what even the calibration wizard ends the problem persist. thanks a lot for your help.

**Comment by ndeadly** [comment] 2021-08-04 23:29
No problem. You could also check the values in Switch mode and see how/if they differ. That should give me some kind of idea of what's actually going on with these controllers

**Comment by impeeza** [comment] 2021-08-05 01:17
Hi, no much luck for now,  

In Switch mode, as expected, the Calibration freezes at end:
![SwitchModeCalibration](https://user-images.githubusercontent.com/41979604/128275345-136e2c29-2cfa-4c32-99d1-4c072ed16d1f.jpg)

the BTDB shows:
![SwitchModePaired](https://user-images.githubusercontent.com/41979604/128275398-c5c10dd8-353c-4528-b4a8-6c65f69f47b3.jpg)

Sticks Center
![SwitchModeAnalogTest-00-Centered](https://user-images.githubusercontent.com/41979604/128275423-18cc47dd-a9a9-49c3-9486-314356021465.jpg)

Left Stick to the Right
![SwitchModeAnalogTest-01-Left-Right](https://user-images.githubusercontent.com/41979604/128275424-acd96493-c290-45fd-804c-c13da8419a57.jpg)

Left Stick Up
![SwitchModeAnalogTest-02-Left-Up](https://user-images.githubusercontent.com/41979604/128275428-03a659de-c99d-430f-816a-3d78ae122f0d.jpg)

Left Stick to the Left
![SwitchModeAnalogTest-03-Left-Left](https://user-images.githubusercontent.com/41979604/128275431-1f9944da-588d-4c46-91ff-287223b3bad9.jpg)

Left Stick Down
![SwitchModeAnalogTest-04-Left-Down](https://user-images.githubusercontent.com/41979604/128275432-08590d5e-1a21-4354-983b-914a9057d6cb.jpg)

Right Stick to the Right
![SwitchModeAnalogTest-05-Right-Right](https://user-images.githubusercontent.com/41979604/128275433-9c7eb552-13e6-49bb-9031-cfd711ae2b66.jpg)

Right Stick Up
![SwitchModeAnalogTest-06-Right-Up](https://user-images.githubusercontent.com/41979604/128275435-4bef9a7b-c949-42a9-8239-6f04fe3af754.jpg)

Right Stick to the Left
![SwitchModeAnalogTest-07-Right-Left](https://user-images.githubusercontent.com/41979604/128275437-f601fd6d-06cb-4ae0-a421-dd3e31f2e736.jpg)

Right Stick Down
![SwitchModeAnalogTest-08-Right-Down](https://user-images.githubusercontent.com/41979604/128275439-ea0e4e87-7288-4f5a-a31d-d71f1fc24a7c.jpg)


But in XBox mode, The pairing works fine:
![XBoxModePaired](https://user-images.githubusercontent.com/41979604/128275721-3de35019-8006-4a0b-9db8-17579d04b73c.jpg)

The Calibration Wizard ends fine:
![XBoxModeCalibration](https://user-images.githubusercontent.com/41979604/128275753-c6bb6cf3-d636-4cdb-a966-bf4b8a2fb943.jpg)

But the Analog Test app show nothing 8-0 :
![XBoxModeAnalogTest](https://user-images.githubusercontent.com/41979604/128275774-74538eaf-e579-4174-b714-add066dfefde.jpg)

**Comment by ndeadly** [comment] 2021-08-05 05:35
Ahh the 8bitdo might use the old Xbox firmware report format which is one byte shorter. I'm lazily using report id and size to determine the controller type. Try this one.

[xbox-analog-stick-test.zip](https://github.com/ndeadly/MissionControl/files/6936132/xbox-analog-stick-test.zip)

Thanks for the thorough reporting so far. I can see that in switch mode that the controller is using the full 12-bit range (0x000-0xfff) of values. Combine this with invalid calibration data and you have the exact issue that Mission Control had with the sticks maxing out too soon. This confirms my suspicions on the switch mode side of things. Now let's see what the XInput mode is doing

**Comment by impeeza** [comment] 2021-08-05 18:23
Hi, I just have a time and make the test, this are the values of Analog Stick Test using my SN 30 Pro+ in X-Input mode:

All Sticks centered>
![XBoxModeAnalogTest-00-Centered](https://user-images.githubusercontent.com/41979604/128401319-e98e8a1d-6091-41aa-a40f-be3d4896971d.jpg)

Left Stick to Right
![XBoxModeAnalogTest-01-Left-Right](https://user-images.githubusercontent.com/41979604/128401320-8656f050-e2bd-49d1-9615-6d0eab7478e3.jpg)

Left Stick UP
![XBoxModeAnalogTest-02-Left-Up](https://user-images.githubusercontent.com/41979604/128401321-82f4acbd-21ae-4541-985b-f4f8ab56ab1a.jpg)

Left Stick to Left
![XBoxModeAnalogTest-03-Left-Left](https://user-images.githubusercontent.com/41979604/128401322-b997bb3f-d00c-4ebe-b3cf-ced0d23b4d18.jpg)

Left Stick Down
![XBoxModeAnalogTest-04-Left-Down](https://user-images.githubusercontent.com/41979604/128401324-e31defa4-5cdf-4b0b-ae15-8f8b3deb59d7.jpg)

Right Stick to Right
![XBoxModeAnalogTest-05-Right-Right](https://user-images.githubusercontent.com/41979604/128401326-80cc586d-f5c1-4acb-a544-e7b3455ffb89.jpg)

Right Stick UP
![XBoxModeAnalogTest-06-Right-Up](https://user-images.githubusercontent.com/41979604/128401330-910a50a3-da74-40c7-93fc-5a7a20999030.jpg)

Right Stick to Left
![XBoxModeAnalogTest-07-Right-Left](https://user-images.githubusercontent.com/41979604/128401332-2b68a986-b31b-406e-8f0e-bed720471639.jpg)

Right Stick Down
![XBoxModeAnalogTest-08-Right-Down](https://user-images.githubusercontent.com/41979604/128401333-8de5c57c-0aac-41bc-b73f-8234e6cc9922.jpg)

Hope this help.  regards.

**Comment by impeeza** [comment] 2021-08-05 18:26
By the way  the RAW values of 0xFFFF are showed on screen when the physical stick hasn't reached the end of his way,  approximated at 80% of the total possible track.

**Comment by ndeadly** [comment] 2021-08-05 18:48
Hmm, this is exactly the behaviour I expected to see from both modes based on the stick issue that I've seen. As far as I can tell the controller is behaving exactly as an Xbox One controller, so the fix *should* be working.

> By the way the RAW values of 0xFFFF are showed on screen when the physical stick hasn't reached the end of his way, approximated at 80% of the total possible track.

If the raw values are maxing out early, that's a somewhat different story. That implies the firmware is applying an outer deadzone or similar and no calibration is going to fix values that are being clamped. This can be observed with an Xbox One controller too though, so it's not necessarily an issue. I'm not sure I'd say it happens as early as 80% of the travel however. Can you notice any difference between the two modes as far as the stick travel goes? Could it be that the fix is actually working, but you expected it to max out bang on 100% travel?

**Comment by impeeza** [comment] 2021-08-05 22:10
Yes, I think that is a 8BitDo issue but really they support is ... (I can't think about a polite epithet)Wish for a Open Source firmware but...

**Comment by ndeadly** [comment] 2021-08-05 22:31
Well thing is, someone told me the controller works fine on PC. But I don't see how that can be any different if the raw values max out early - you've still got a portion of the stick travel where the values don't change. In any case, I would assume my changes are probably actually working as expected based on what you've showed me. Did you compare whether the point the sticks max out in the calibration screen is the same between the two modes? I would expect XInput mode to be marginally better than Switch mode

**Comment by impeeza** [comment] 2021-08-05 22:45
You make think about pc.  I will test on pc this night

**Comment by impeeza** [comment] 2021-08-11 01:02
Hi, sorry for delay, long weekend, I just connect my SN30 Pro+ to a Windows Computer, then using joy.cpl try to calibrate the controller and the bad news are:  for the left stick the values of RAW Data goes from 0 to 255 on each axis, but the 0 (left & up) and 255 (right and down) values are show when the physical stick reaches approximated 70% of all the possible movement, so the bad values and early top of each axis is a hardware/firmware problem, I don't think that can be solved with drivers.
Same occurs to the right stick, what are mapped to Z axis and Z Rotation.

On X-input mode the RAW values are from 0 to 65535 but the problem persist.

on D-Input mode I couldn't test because Windows doesn't recognize the controller as a Windows one.

On Switch modes is the same  but the values goes from 0 to 65280.

**Closed** 2021-11-02 01:46 UTC
