### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by thejocraftkit** [ndeadly/MissionControl#584] opened 2023-02-14 20:23 UTC
### Controller Name

XBOX SERIES S/X

### Current Controller Behaviour

Other (please specify below)

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Hello I am requesting a controller (XBOX SERIES S/X) for the switch because its the only one I have  i know that they use a different Bluetooth module but can you please make a program that detects them and converts it into the switches moduöe

**Comment by Masamune3210** [comment] 2023-02-14 21:16
They are Bluetooth LE, will have to wait until patches supporting LE can be figured out, unfortunately. If you have any other controllers, you will likely have a better chance getting them either supported or connected in the meantime

**Comment by ndeadly** [comment] 2023-02-14 22:14
Duplicate of #135

**Closed** 2023-02-14 22:14 UTC
Labels: controller request
