### ISSUE TITLE
[Controller Request]: flydigi apex 2 

### ISSUE THREAD

**Issue by Pras75** [ndeadly/MissionControl#789] opened 2024-03-15 22:34 UTC
### Controller Name

Flydigi apex 2 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Controller vendor and product ID

Flydigi 

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

Hay i have this controler for years and i moded my console last month and i hope i can use it, but sadly not 😅. so i hope you can help me, i Really appriciate it 
![IMG_20240311_141821](https://github.com/ndeadly/MissionControl/assets/50307344/981a19e6-ed8c-4365-a1f0-0069f2db6e6c)

**Comment by ndeadly** [comment] 2024-03-25 09:57
Duplicate of #670 

This one is working already in the private BLE test builds on my discord server.

**Closed by ndeadly** 2024-03-25 09:57 UTC
Labels: controller request
