### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by ActiveSierro** [ndeadly/MissionControl#869] opened 2024-10-10 08:43 UTC
### Controller Name

Ultimate 2C Wireless Controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

https://shop.8bitdo.com/products/ultimate-2c-black-myth-wukong

**Comment by ndeadly** [comment] 2024-10-10 08:45
Duplicate of #851 

This is another BLE controller. Supported already in private

**Closed by ndeadly** 2024-10-10 08:45 UTC
Labels: controller request

**Comment by ndeadly** [comment] 2024-10-10 09:11
When BLE support is complete. Work-in-progress builds are available on my discord server
