### ISSUE TITLE
compatibility with SX OS 

### ISSUE THREAD

**Issue by ElJavid** [ndeadly/MissionControl#106] opened 2020-10-03 15:37 UTC
compatibility with SX OS

**Comment by ndeadly** [comment] 2020-10-03 15:42
*sigh*

Duplicate of #23 #25 #32 #37 #41 #46 #82 #96

**Closed by ndeadly** 2020-10-03 15:42 UTC

**Comment by ndeadly** [comment] 2020-10-03 15:43
With the recent arrests of head TX members you'll probably never see SXOS supporting MissionControl. I suggest you start looking into switching to Atmosphere.

**Comment by ElJavid** [comment] 2020-10-03 21:29
> With the recent arrests of head TX members you'll probably never see SXOS supporting MissionControl. I suggest you start looking into switching to Atmosphere.
I know but i cant install ir play games cracked with atmosphere

**Comment by Masamune3210** [comment] 2020-10-03 21:59
Who told you that? you just have to figure out how somewhere else as piracy isnt supported. In either case, its not a problem of this project
