### ISSUE TITLE
[Bug Report]: Disconnect after leaving Change Grip menu

### ISSUE THREAD

**Issue by taoorus** [ndeadly/MissionControl#417] opened 2022-01-07 12:16 UTC
### Switch Firmware Version

13.2.0 (Latest)

### Atmosphère Version

1.2.5 (Latest)

### Mission Control Version

0.6.3 (Latest)

### Boot Method

Hekate

### Issue Description

When I connect my Xiaomi Mi Controller in Change Grip menu it connects but after pressing A it immediately disconnects. But if i connect it in background it connects and i can play as long as there is no other window Change Grip. 

Also if controller is connected and I manually go to Change Grip menu - controller immediately disconnects.

### Additional Context

I tried 
- deleting mission control
- removing pairing
- changing batteries
- reloading switch
- pressing A in this menu by touch or with other controller

**Comment by ndeadly** [comment] 2022-01-07 12:19
Duplicate of https://github.com/ndeadly/MissionControl/issues/401

This has been resolved and will be fixed in the next release. You can find a working build in the thread above https://github.com/ndeadly/MissionControl/issues/401#issuecomment-986210348

**Closed by ndeadly** 2022-01-07 12:19 UTC
