### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by vink2212** [ndeadly/MissionControl#669] opened 2023-07-08 16:41 UTC
### Feature Description

Dualsense haptics for HD rumble.

### Rationale

The dualsense controller has better haptics than the joycon/pro controller, would it be possible to send the HD rumble signals to the dualsense to emulate/have hd rumble. 
The current rumble is already quite good but if we could push it a step further and have similar feedback to what the pro controller offers that would be amazing.

**Comment by ndeadly** [comment] 2023-07-13 19:34
Duplicate of #610

**Closed** 2023-07-13 19:34 UTC
Labels: feature request
