### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by matthiasnielsen1** [ndeadly/MissionControl#569] opened 2023-01-17 22:29 UTC
### Controller Name

Google Stadia

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [X] Battery Level Reporting

### Additional Details

I don’t know much. Just know that Google made it possible today, converting Stadia controller to Bluetooth. And I lot of people would love using it on their switch instead. 

https://stadia.google.com/controller

**Comment by ndeadly** [comment] 2023-01-17 22:36
Duplicate of #568

**Closed by ndeadly** 2023-01-17 22:36 UTC
Labels: controller request
