### ISSUE TITLE
I can't use arrow

### ISSUE THREAD

**Issue by North010** [ndeadly/MissionControl#62] opened 2020-09-10 12:26 UTC
When I take a arrow (Skyrim and Zelda BOTW).My camera starts to turn up-right-left-down so my game's annoying.

**Comment by Conan179** [comment] 2020-09-10 12:33
Which controller?

**Comment by North010** [comment] 2020-09-10 12:38
Dualshock 4

**Comment by ndeadly** [comment] 2020-09-10 13:42
Duplicate of #15 

This is fixed in the upcoming release. You can either disable motion controls ingame, install the build posted in the issue linked above, or wait for the next release.

**Closed** 2020-09-10 13:43 UTC
Labels: duplicate
