### ISSUE TITLE
[Feature Request]: Support for using motion controllers in Nintendo Switch Sports

### ISSUE THREAD

**Issue by kylefmohr** [ndeadly/MissionControl#461] opened 2022-04-30 21:02 UTC
### Feature Description

I haven't been able to find my MotionPlus WiiMote to test, but I tried the DualShock 4 and the WiiMote with the new Nintendo Switch Sports game and they don't work. Similar to if you try to play with a Switch Pro controller, [this screen comes up](https://imgur.com/a/X0CKLAR) and won't allow you to advance unless you connect detached joycons. 

It would be especially cool to use the WiiMotes for this game. Can somebody with a MotionPlus attachment or MotionPlus built-in WiiMote test and see if allows you to start a game? 

I'm guessing you'd have to have the controller emulate a single joy-con, and this is rarely the desired play method, but if there were a way to toggle this feature, that'd be pretty neat. 

### Rationale

I'm not sure if this is useful outside of Switch Sports, but imo the WiiMotes make a better controller than the joy-cons for this type of motion game. I think others would agree.

**Comment by ndeadly** [comment] 2022-05-03 03:54
Somebody already requested this a few days ago https://github.com/ndeadly/MissionControl/issues/458

I closed that issue as it's essentially a duplicate of the more general problem of "allow controllers to pretend to be joycons", which there is already an issue tracking here https://github.com/ndeadly/MissionControl/issues/108

**Closed by ndeadly** 2022-05-03 03:54 UTC
Labels: feature request

**Comment by kylefmohr** [comment] 2022-05-03 04:20
Sounds good, I looked through a few issues before submitting but didn't see that one, sorry for the duplicate. Thanks for all of your hard work 😁
