### ISSUE TITLE
[Controller Request]: 8Bitdo Ultimate 2C

### ISSUE THREAD

**Issue by KrabbyNgwyn** [ndeadly/MissionControl#883] opened 2024-10-31 15:21 UTC
### Controller Name

8Bitdo Ultimate 2C

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [x] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

Link: https://www.8bitdo.com/ultimate-2c-wireless-controller/
please support! Really appriciated <3

**Comment by ndeadly** [comment] 2024-10-31 15:24
Duplicate of #851 

Controller is a BLE device and already supported in private

**Closed by ndeadly** 2024-10-31 15:24 UTC
Labels: controller request
