### ISSUE TITLE
[Controller Request]: Request support

### ISSUE THREAD

**Issue by 1824770736** [ndeadly/MissionControl#862] opened 2024-09-16 02:46 UTC
### Controller Name

Google Stadia

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [ ] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment] 2024-09-16 05:44
Duplicate of #568

**Closed** 2024-09-16 05:45 UTC
Labels: controller request
