### ISSUE TITLE
[Bug Report] [MC 0.6.1] Dualshock 4 random rumble and issues

### ISSUE THREAD

**Issue by zxUli** [ndeadly/MissionControl#385] opened 2021-10-29 03:29 UTC
### Switch Firmware Version

13.1.0 (Latest)

### Atmosphère Version

1.2.1 (Latest)

### Mission Control Version

Other (please specify in issue description)

### Boot Method

Fusée

### Issue Description

[Mission Control ver 0.6.1]

Hi, first at all thanks you very much for the effort and time for doing this, it has allowed to have awesome fun with my friends at the job playing some Fifa tourneys with my DS4's.

About the issue(s) would be the following:

Mission Control worked perfectly fine with my Dualshock 4 before the HOS update (13.1.0) but now its working in a weird way

- It's a bit hard to get the controller paired, sometimes it just wont pair and other times it will pair.

(the next is the big one) 
- When paired around 3 out of 4 times it will randomly rumble without stoping, sometimes it rumbles strong and sometimes it lowers its intensity, usually when i change to another menu either in a game or in the Home section.
[Edit: it keeps rumbling even when i deactivate the rumble feature on the HOS setting]

- When it pairs and doesnt randomly rumble i noticed that the controller has both a 'longer' rumble when the game sends the instruction, like when firing a weapon on a FPS, it will also be very slighty delayed.

ie: When firing a Pistol on DOOM (1993, bethesda ver.) the Rumble starts like about 1/2 second later and instead of rumbling for 1 seconds, it would rumble like for 2 or 3 seconds.

That would be from what i experienced so far, thanks for the good work ! 

PD: going to leave a Ko-fi don as soon as i can ;)

**Comment by Lagmobile** [comment] 2021-10-30 17:34
Confirming the same issue. I was playing Mario Party Superstars for several hours, solo, without any issue. Then I tried to connect a pair of joy cons for a friend who wanted to play and the random rumbling started.

It varies in intensity for random intervals and for random amounts of time. Sometimes it will start strong then gradually decrease in intensity, as if it was winding down, then increase again in the same way or even instantly. Random in every sense of the word. 

Also happens regardless of the actions on screen.

**Comment by YunoGasai67** [comment] 2021-10-31 01:26
This seems to be an issue with Atmos 1.2.2, as I also had issues with the regular joycon being recognized as a pro controller, individually for each joycon

**Comment by rodolfostanic** [comment] 2021-11-01 03:06
Having the same issues when using version 0.6.1 with Atmosphere 1.2.2.

**Comment by GiGis-Khan** [comment] 2021-11-01 12:58
same problem here i just updated my console and it started having this issue

**Comment by Bazbhoy1888** [comment] 2021-11-01 14:01
Same issue with PS4 vibrating like mad and seems to be constant

**Comment by ndeadly** [comment] 2021-11-01 19:35
@zxUli thanks for the detailed report. I spent the weekend looking into this. It resembles an issue that has existed for Wii controllers for a while where on certain screens controllers would start vibrating nonstop if an official controller was connected as player one, only now appears to happen for all controllers. Super strange issue that seems to have something to do with the data buffer I stage the converted rumble packets onto becoming corrupted. Even stranger because I barely changed any code between 0.6.0 and 0.6.1, and what _was_ changed had nothing to do with rumble.

Anyhow, I modified the code to give each controller it's own buffer for staging purposes and as far as I can tell the problem has gone away on the home screen. I suspect however, that you may possibly be reporting several individual issues. I tested
 with an in-game issue such as https://github.com/ndeadly/MissionControl/issues/354 and that problem still persists.

Try this build out and let me know how it helps. You will probably need to make sure you're running Atmosphere 1.2.2
[MissionControl-0.6.1-develop-b1d9fc9.zip](https://github.com/ndeadly/MissionControl/files/7455677/MissionControl-0.6.1-develop-b1d9fc9.zip)

> It's a bit hard to get the controller paired, sometimes it just wont pair and other times it will pair.

I have noticed DS4 pairing seems a little less reliable than before. No idea what changed, it wasn't my code. In general, hitting the reset button on the back of the controller before pairing can improve the situation. You do know you don't have to pair the controller every time you connect, right? It's enough to hit the PS button after the initial pairing.

**Comment by zxUli** [comment] 2021-11-01 20:08
> 
> 
> @zxUli thanks for the detailed report. I spent the weekend looking into this. It resembles an issue that has existed for Wii controllers for a while where on certain screens controllers would start vibrating nonstop if an official controller was connected as player one, only now appears to happen for all controllers. Super strange issue that seems to have something to do with the data buffer I stage the converted rumble packets onto becoming corrupted. Even stranger because I barely changed any code between 0.6.0 and 0.6.1, and what _was_ changed had nothing to do with rumble.
> 
> Anyhow, I modified the code to give each controller it's own buffer for staging purposes and as far as I can tell the problem has gone away on the home screen. I suspect however, that you may possibly be reporting several individual issues. I tested with an in-game issue such as #354 and that problem still persists.
> 
> Try this build out and let me know how it helps. You will probably need to make sure you're running Atmosphere 1.2.2 [MissionControl-0.6.1-develop-b1d9fc9.zip](https://github.com/ndeadly/MissionControl/files/7455677/MissionControl-0.6.1-develop-b1d9fc9.zip)
> 
> > It's a bit hard to get the controller paired, sometimes it just wont pair and other times it will pair.
> 
> I have noticed DS4 pairing seems a little less reliable than before. No idea what changed, it wasn't my code. In general, hitting the reset button on the back of the controller before pairing can improve the situation. You do know you don't have to pair the controller every time you connect, right? It's enough to hit the PS button after the initial pairing.

Thanks a lot, going to try that build asap and i will report about the results ;)

**Comment by zxUli** [comment] 2021-11-01 20:35
@ndeadly , so i tried the Build you suggested me and its working super good now !  

I tested it on the following games:

- Fifa 21
- Quake
- Doom 2
- Xeno Crisis

Thanks a lot for the hard work buddy !

**Comment by ndeadly** [comment] 2021-11-01 20:47
Nice. I'll commit these changes then and make a bugfix release in a few days. Let me know if any other issues arise/persist

**Comment by Bazbhoy1888** [comment] 2021-11-01 21:06
Just tried your development build works perfect thanks so much for your hard work

**Comment by rodolfostanic** [comment] 2021-11-02 22:45
@ndeadly For some reason, even when using the dev build, I still get the same constant rumbling on my DS4 controller, but this time randomly.

The problem is solved by clicking on "Change Grip/Order" and reconnecting, but can happen again when I try to reconnect after sleep mode, for instance.

**Comment by ndeadly** [comment] 2021-11-02 22:50
@rodolfostanic I think there are multiple issues with rumble, you may be describing one of the other ones that hasn't been resolved with the fix above (I still get a constant but variable amplitude vibration playing crash team racing for example). Where does the rumble occur? Home menu or in-game? Does it happen with or without other controllers connected?

**Comment by rodolfostanic** [comment] 2021-11-02 22:56
> @rodolfostanic I think there are multiple issues with rumble, you may be describing one of the other ones that hasn't been resolved with the fix above (I still get a constant but variable amplitude vibration playing crash team racing for example). Where does the rumble occur? Home menu or in-game? Does it happen with or without other controllers connected?

It happens on the home menu and usually when the joycons are connected via bluetooth as well.

**Comment by ndeadly** [comment] 2021-11-02 23:09
Are you certain you copied the dev build over correctly and rebooted? This sounds just like the issue I was having until the fix, but I did a fair bit of testing and wasn't able to trigger it again after making the changes.

Otherwise, if you can come up with instructions how to reliably reproduce it I'll try to look into it.

**Comment by rodolfostanic** [comment] 2021-11-03 00:38
No problem, I will try to find a pattern in this behavior so I can help you reproduce it. Right now, it seems a little random.

**Comment by ndeadly** [comment] 2021-11-03 00:47
> No problem, I will try to find a pattern in this behavior so I can help you reproduce it. Right now, it seems a little random.

For me, it seemed to have something to do with being in the controller menu, with an official controller connected as player one and then connecting the other. Maybe this gives you a starting point.

**Comment by sonik-br** [comment] 2021-11-03 11:55
I don't know if it's related but for me when using a DualSense when playing Metroid, sometimes the it starts the rumble effect won't turn the effect off. It will only turn off when another rumble effect overrides the previous.
Switch on latest firm, MC 0.6.1 and Atmosphere 1.2.2.

**Comment by ndeadly** [comment] 2021-11-03 13:13
> I don't know if it's related but for me when using a DualSense when playing Metroid, sometimes the it starts the rumble effect won't turn the effect off. It will only turn off when another rumble effect overrides the previous. Switch on latest firm, MC 0.6.1 and Atmosphere 1.2.2.

Did you try with the build posted above? Issues are to be expected on the release build, as that's exactly what this issue is reporting on

**Comment by sonik-br** [comment] 2021-11-03 13:18
Oh... I missed that. Gonna try and report back. Thanks!

**Comment by ndeadly** [comment] 2021-11-03 17:50
This build appears to fix the issue people had reported with Crash Team Racing (and possibly other games) by setting rumble amplitude to zero in places where the rumble motor data has a high frequency value lower than the low frequency. This is a potentially naive approach, as I have no idea whether this is a valid condition for other games.

Please test to see whether it helps with any of the outstanding rumble issues, and maybe more importantly, whether the fix negatively impacts rumble in any way in games without existing issues.

[MissionControl-0.6.1-rumble-fix-d8cac87.zip](https://github.com/ndeadly/MissionControl/files/7469723/MissionControl-0.6.1-rumble-fix-d8cac87.zip)

**Comment by sonik-br** [comment] 2021-11-05 12:52
This fixed it for me :)
Also, no collateral damage. But I only tested on metroid...

**Comment by OperationNT414C** [comment] 2021-11-07 15:16
On "Astria Ascending", the rumble bug since 0.6.1 is highly severe: when a rumble is triggered, it never stop until the next rumble command.
So I tested "MissionControl-0.6.1-rumble-fix-d8cac87.zip" on this game : the problem is that, now, there is no rumble at all. :-(

About my test on Metroid Dread, it feels like this fix triggers far less rumble strength that there was on 0.6.0. But maybe, it's just a feeling (now that I am on Atmosphere 1.2.2, I cannot easily test the previous version).

**Comment by everyonesweird** [comment] 2021-11-08 03:08
> On "Astria Ascending", the rumble bug since 0.6.1 is highly severe: when a rumble is triggered, it never stop until the next rumble command. So I tested "MissionControl-0.6.1-rumble-fix-d8cac87.zip" on this game : the problem is that, now, there is no rumble at all. :-(
> 
> About my test on Metroid Dread, it feels like this fix triggers far less rumble strength that there was on 0.6.0. But maybe, it's just a feeling (now that I am on Atmosphere 1.2.2, I cannot easily test the previous version).
> 
> EDIT: I tested "MissionControl-0.6.1-develop-b1d9fc9.zip":
> 
> * On Metroid Dread, it indeed fix the rumble issue
> * But on Astria Ascending, it doesn't work (same issue as original 0.6.1)

Update ATMS to 1.2.4 and try again. Had same issue but this new Rumble fix build solved mine.

**Comment by OperationNT414C** [comment] 2021-11-08 22:42
> Update ATMS to 1.2.4 and try again.

Unfortunately, going to Atmosphère 1.2.4 did not change the fact that the "rumble-fix" version completly turns off vibrations in "Astria Ascending".

**Comment by ndeadly** [comment] 2021-11-08 23:20
I would not expect Atmosphère version to play any part in this.

@OperationNT414C could you run this build with debug logging enabled while playing yout game with a wireless controller and post it here? I want to see what the rumble packets look like. The log file (`sdmc:/mc-mitm.log`) is inaccessible while the console is running, so you will need to reboot into hekate UMS or power down and read your sd card externally to retrieve it.

[MissionControl-0.6.1-dbg-93a377d.zip](https://github.com/ndeadly/MissionControl/files/7500696/MissionControl-0.6.1-dbg-93a377d.zip)

**Comment by OperationNT414C** [comment] 2021-11-08 23:25
Sorry, now it's late in my country: I won't be able to check that until 20 hours. I will give you a feedback tomorrow.

**Comment by GiGis-Khan** [comment] 2021-11-09 13:02
@ndeadly i have installed the fix and the rumble has stopped i tested in several games with 2 ps4 controllers an 2 joycons (games super mario 3d world, mario party superstars, super smash bros, n64 emutalor, mario tenis aces , and golf ) it is buttery smoth now thanks.
also i needed to update atmosphere to the latests version !!!!  AMS1.2.4 firmware 13.1.0

**Comment by OperationNT414C** [comment] 2021-11-09 18:07
> [MissionControl-0.6.1-dbg-93a377d.zip](https://github.com/ndeadly/MissionControl/files/7500696/MissionControl-0.6.1-dbg-93a377d.zip)

Unfortunatly, this version crashes as soon as I power up my DS4 controller. See attached zip (contains the crash report):
[0.6.1-dbg_crash.zip](https://github.com/ndeadly/MissionControl/files/7507015/0.6.1-dbg_crash.zip)

**Comment by ndeadly** [comment] 2021-11-10 18:10
@OperationNT414C sorry about that. I just hacked in the changes for logging rumble packets for official controllers and forgot to test it with unofficial ones. This one should work.

[MissionControl-0.6.1-dbg-4ab2d65.zip](https://github.com/ndeadly/MissionControl/files/7515002/MissionControl-0.6.1-dbg-4ab2d65.zip)

**Comment by OperationNT414C** [comment] 2021-11-10 19:22
This version is fine, please find the log file as attachment.
[mc-mitm.log](https://github.com/ndeadly/MissionControl/files/7515362/mc-mitm.log)

I see that it contains a lot of rumble packets. I let you analyse but without timestamp dump, it could be complex? What I can tell you is that, in this game (turn by turn RPG), the rumbles are not longer than 1 sec (when an enemy strikes one of your characters).

**Comment by ndeadly** [comment] 2021-11-10 22:28
Thanks. Timestamps are unimportant, I just want to see the range of values that it sends that can be considered valid to see how my current strategy for stopping the errant rumble packets in the crash games is killing it entirely for this game.

**Comment by nickyvalentino** [comment] 2021-11-12 08:04
hi , im still getting fatal error occured , even with latest build 4ab2d65

**Comment by SnakeBabu** [comment] 2021-11-13 22:28
Hello i take the MissionControl-0.6.1-dbg-4ab2d65.zip but i have crash ( fatal_error). I clear in my sd file for mission control and rest my PS4 control but is crased when i try to sychronize . i send the file .bin ( sorry for my english )
[report_00000000c10904fb.zip](https://github.com/ndeadly/MissionControl/files/7532863/report_00000000c10904fb.zip)

**Comment by otto-dev** [comment] 2021-11-16 03:59
Can confirm that out-of-place / constant vibrating issue with the PS5 DualSense controller appear resolved as well with `missioncontrol-0.6.1-dbg-4ab2d65.zip`.

**Comment by ndeadly** [comment] 2021-11-16 09:46
`MissionControl-0.6.1-dbg-4ab2d65.zip`  is just the previous one with the rumble fixes applied, built with some logging added on top. You shouldn't really be using it for anything other than generating debug logs, as the logging degrades performance.

After viewing the log from @OperationNT414C and making a few of my own, I think I now understand the cause of the remaining issues. I just haven't had much free time in the past week to make the changes and put out a release.

**Comment by ndeadly** [comment] 2021-11-16 23:21
One more build to try that hopefully addresses the last of the issues. Try it out and give me some feedback. If all is good I'll put out a release soon. Particularly, @OperationNT414C could you let me know if it fixes the problem with Astria Ascending?

[MissionControl-0.6.1-develop-eeb37b0.zip](https://github.com/ndeadly/MissionControl/files/7550517/MissionControl-0.6.1-develop-eeb37b0.zip)

**Comment by OperationNT414C** [comment] 2021-11-16 23:41
It works great on Astria Ascending: the rumbles are present with the appropriate duration.
Thank you very much!

**Comment by otto-dev** [comment] 2021-11-17 03:13
Amazing work @ndeadly! Thanks. Looking forward to using it.

**Comment by ndeadly** [comment] 2021-11-17 10:40
The fixes from this thread have now been included in the v0.6.2 release. Hopefully that's everything addressed. Enjoy!

**Closed by ndeadly** 2021-11-17 10:40 UTC
