### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by adrirogi07** [ndeadly/MissionControl#676] opened 2023-07-15 17:24 UTC
### Controller Name

8bitdo ultimate 2,4gh bluethoot mode

### Current Controller Behaviour

Controller successfully pairs with the console but doesn't respond to inputs

### Controller vendor and product ID

2dc8:3012

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

### Additional Details

not the same as the ultimate wireless controlles, this one has bluethoot but is not switch compatible. Contact me if you need the input report format

**Comment by ndeadly** [comment] 2023-07-15 17:27
Duplicate of https://github.com/ndeadly/MissionControl/issues/640

Support has already been added, it will be officially available in the next release. Until then you can find a working build in the issue linked above.

**Closed by ndeadly** 2023-07-15 17:27 UTC
Labels: controller request

**Comment by adrirogi07** [comment] 2023-07-15 17:32
thanks
