### ISSUE TITLE
[Controller Request]:

### ISSUE THREAD

**Issue by BrendanCG** [ndeadly/MissionControl#549] opened 2022-12-20 06:00 UTC
### Controller Name

moga xp5-x plus

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment] 2022-12-20 12:06
Duplicate of https://github.com/ndeadly/MissionControl/issues/50

**Closed by ndeadly** 2022-12-20 12:06 UTC
Labels: controller request
