### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by NotArialdy** [ndeadly/MissionControl#738] opened 2023-10-16 14:57 UTC
### Controller Name

Xbox Series X controller 

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [ ] Motion Controls
- [ ] Player Number Indicator
- [ ] Battery Level Reporting

**Comment by ndeadly** [comment] 2023-10-16 14:58
Duplicate of https://github.com/ndeadly/MissionControl/issues/135

**Comment by ndeadly** [comment] 2023-10-16 14:59
Duplicate of https://github.com/ndeadly/MissionControl/issues/135

**Closed by ndeadly** 2023-10-16 14:59 UTC
Labels: controller request
