### ISSUE TITLE
[Controller Request]: 

### ISSUE THREAD

**Issue by kevinkk12** [ndeadly/MissionControl#816] opened 2024-05-14 15:22 UTC
### Controller Name

afterglow Wii u pro controller

### Current Controller Behaviour

Controller is not successful in pairing with the console

### Supported Features

- [X] Rumble/Vibration
- [X] Motion Controls
- [X] Player Number Indicator
- [X] Battery Level Reporting

**Comment by ndeadly** [comment] 2024-05-14 15:27
Duplicate of #327, #585

IIRC, these controllers don't show up during device discovery.

**Closed by ndeadly** 2024-05-14 15:27 UTC
Labels: controller request

**Comment by kevinkk12** [comment] 2024-05-14 15:32
> Duplicate of #327, #585
> 
> IIRC, these controllers don't show up during device discovery.

**Comment by kevinkk12** [comment] 2024-05-14 15:33
> Duplicate of #327, #585
> 
> IIRC, these controllers don't show up during device discovery.

I can't connect it even via USB?

**Comment by ndeadly** [comment] 2024-05-14 15:34
Does it work via USB on PC? Official Nintendo Wii U Pro controllers only support charging via USB

**Comment by kevinkk12** [comment] 2024-05-14 22:19
> Does it work via USB on PC? Official Nintendo Wii U Pro controllers only support charging via USB

It connects to the PC, and detects it, but when I turn it on it disconnects instantly

**Comment by ndeadly** [comment] 2024-05-14 22:22
So no, I guess. Official controllers expose an HID interface that the PC will probably pick up, but it doesn't actually do anything except periodically send 0x00 to the host (or something like that)
