### ISSUE TITLE
Sony Control Dualshock 3 will it be compatible in the future?

### ISSUE THREAD

**Issue by skins20** [ndeadly/MissionControl#166] opened 2020-12-25 18:31 UTC

**Comment by Valengarnic** [comment] 2020-12-25 18:53
_**Can you add support for PS3 controllers?** I won't rule out a solution in the future, but this is not high priority for me right now. Sorry DS3 owners._

**Comment by ndeadly** [comment] 2020-12-25 21:59
Duplicate of #7 

The quote posted above by Valengarnic is taken from the FAQ in the project readme. You can find the full explanation of the situation with the Dualshock 3 there. In short - it's probably a lot of work and I can't justify spending time on it at this time.

**Closed by ndeadly** 2020-12-25 21:59 UTC
